### ISSUE TITLE
[SUGGESTION] Packet Mechanic

### ISSUE THREAD

**Issue by Arian100** [oraxen/oraxen#1011]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

With this you could send Packets as a Mechanic. Ik it would take at least a decent amount of effort to make but would greatly enhance the plugin. It could look something like this:
```
// Item...
Mechanics:
  Play.Server.GAME_STATE_CHANGE:          // packet
    - 0, int, "10"           // index, datatype, value
    - 0, float, "1.0F"
 Play.Server.SET_TITLE_TEXT:
    - 0, String, "Hi!"
 Play.Server.PLAYER_INFO:
    - 0, "PlayerInfoAction", "ADD_PLAYER"           // type, value
    - 0, "GameProfile", ["random", "Name123"]           // type, [UUID, name]
```
This is like in ProtocolLib when you send a Packet. You also could add a way to target specific Players or all Players

### Reason

It would make the Plugin a lot better and also add almost infinite possibilities.
