### ISSUE TITLE
[BUG] First stage of crops drop themselves upon breaking

### ISSUE THREAD

**Issue by cm4500** [oraxen/oraxen#1030]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

While most of the function of crops now works as intended, there is still a minor bug with the first stage of the crops. When seeds are placed and the first stage appears, breaking this will have the intermediate crop stage drop itself, instead of dropping seeds or whatever item you assign it. 

If the dropped crop stage is picked up, placed, and broken again, THEN the correct item will drop. 

Strangely, this only occurs with the first initial stage, and once it progresses to the next stage and onward, breaking those will drop the assigned item - in my case, strawberry seeds and strawberries (for the final stage). 

### Steps to reproduce

```
strawberry_seeds:
  displayname: <#FFFFFF>Strawberry Seeds
  material: PAPER
  Mechanics:
    furniture:
      item: strawberry_stage1
      barrier: false
      farmblock_required: false
      limited_placing:
        roof: false
        floor: true
        wall: false
        type: ALLOW
        block_types:
        - FARMLAND
      evolution:
        delay: 0
        probability: 1.0
        light_boost: false
        next_stage: strawberry_stage1
      drop:
        loots:
        - oraxen_item: strawberry_seeds
          probability: 1.0
      type: DISPLAY_ENTITY
  Pack:
    generate_model: true
    parent_model: item/generated
    textures:
    - default/crops/strawberry/strawberry_seeds
    custom_model_data: 1080

strawberry_stage0:
  material: PAPER
  displayname: <#FFFFFF>Strawberry Stage 0
  excludeFromInventory: true
  Mechanics:
    furniture:
      evolution:
        delay: 100
        probability: 1.0
        light_boost: false
        next_stage: strawberry_stage1
      drop:
        loots:
        - oraxen_item: strawberry_seeds
          probability: 1.0
      type: DISPLAY_ENTITY
  Pack:
    generate_model: false
    model: default/crops/strawberry/strawberry_stage0
    custom_model_data: 1082

strawberry_stage1:
  material: PAPER
  displayname: <#FFFFFF>Strawberry Stage 1
  excludeFromInventory: true
  Mechanics:
    furniture:
      barrier: false
      farmblock_required: false
      evolution:
        delay: 100
        probability: 1.0
        light_boost: false
        next_stage: strawberry_stage2
      drop:
        silktouch: false
        loots:
        - oraxen_item: strawberry_seeds
          probability: 1.0
      type: DISPLAY_ENTITY
  Pack:
    model: default/crops/strawberry/strawberry_stage1
    custom_model_data: 1079

strawberry_stage2:
  material: PAPER
  displayname: <#FFFFFF>Strawberry Stage 2
  excludeFromInventory: true
  Mechanics:
    furniture:
      barrier: false
      farmblock_required: false
      evolution:
        delay: 100
        probability: 1.0
        light_boost: false
        next_stage: strawberry_stage3
      limited_placing:
        roof: false
        floor: true
        wall: false
        type: ALLOW
        block_types:
        - FARMLAND
      drop:
        silktouch: false
        loots:
        - oraxen_item: strawberry_seeds
          probability: 1.0
      type: DISPLAY_ENTITY
  Pack:
    model: default/crops/strawberry/strawberry_stage2
    custom_model_data: 1083

strawberry_stage3:
  material: PAPER
  displayname: <#FFFFFF>Strawberry Stage 3
  excludeFromInventory: true
  Mechanics:
    furniture:
      barrier: false
      farmblock_required: false
      evolution:
        delay: 100
        probability: 1.0
        light_boost: false
        next_stage: strawberry_stage4
      drop:
        silktouch: false
        loots:
        - oraxen_item: strawberry_seeds
          probability: 1.0
      type: DISPLAY_ENTITY
  Pack:
    model: default/crops/strawberry/strawberry_stage3
    custom_model_data: 1084

strawberry_stage4:
  material: PAPER
  displayname: <#FFFFFF>Strawberry Stage 4
  excludeFromInventory: true
  Mechanics:
    furniture:
      barrier: false
      farmblock_required: false
      evolution:
        probability: 1.0
        light_boost: false
      drop:
        loots:
        - oraxen_item: strawberry
          probability: 1.0
        - oraxen_item: strawberry
          probability: 0.5
        - oraxen_item: strawberry
          probability: 0.15
        - oraxen_item: strawberry_seeds
          max_amount: 3
          probability: 1.0
      type: DISPLAY_ENTITY
  Pack:
    model: default/crops/strawberry/strawberry_stage4
    custom_model_data: 1085

```

This crop mechanic format is essentially copied from the Oraxen tutorial doc. 

### Plugin Version

20.08 03:56:18 [Server] [INFO] Oraxen version 1.160.0
20.08 03:56:18 [Server] [INFO] Authors: th0rgal and boy0000

### ProtocolLib Version

20.08 03:55:56 [Server] [INFO] ProtocolLib version 5.1.0
20.08 03:55:56 [Server] [INFO] Provides read/write access to the Minecraft protocol.
20.08 03:55:56 [Server] [INFO] Authors: dmulloy2 and comphenix

### Server Software & Version

20.08 03:58:45 [Server] [INFO] This server is running Paper version git-Paper-"483368e" (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 483368e on ver/1.19.4)

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects
