### ISSUE TITLE
[BUG] Noteblock placed on a specific block turns into a custom block

### ISSUE THREAD

**Issue by SFlakeZ** [oraxen/oraxen#1046]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

**Test on a staging environment with a custom oraxen setup:**

- paper-global.yml -> `disable-noteblock-updates: false`
- Note 0 - custom block
- https://youtu.be/yjHeDgmYASA

**Test on a blank environment with the default oraxen setup + protocollib:**

- paper-global.yml -> `disable-noteblock-updates: false`
- Note 0 - custom block
- https://youtu.be/nSLaphfzv7Q

- paper-global.yml -> `disable-noteblock-updates: true`
- https://youtu.be/IOOvQrsGJrU

### Steps to reproduce

Create ores/blocks till you reach for example `custom_variation: 24`
There are many more where you can hit `note: 0`
```yml
orax_ore_21:
  displayname: <gradient:#3685EC:#72C1E4>Orax Ore 21
  material: PAPER
  Pack:
    generate_model: true
    parent_model: block/cube_all
    textures:
    - default/orax_ore
    custom_model_data: 1024
  Mechanics:
    noteblock:
      block_sounds:
        break_sound: block.stone.break
        place_sound: block.stone.place
      custom_variation: 24
      model: orax_ore
      hardness: 8
      drop:
        silktouch: true
        fortune: true
        minimal_type: IRON
        best_tools:
        - PICKAXE
        loots:
        - oraxen_item: orax
          probability: 1.0
```

### Plugin Version

```
[20:29:55 INFO]: Oraxen version 1.161.0
[20:29:55 INFO]: Authors: th0rgal and boy0000
```

### ProtocolLib Version

```
[20:30:05 INFO]: ProtocolLib version 5.1.0
[20:30:05 INFO]: Provides read/write access to the Minecraft protocol.
[20:30:05 INFO]: Authors: dmulloy2 and comphenix
```

### Server Software & Version

```
[20:29:28 INFO]: Checking version, please wait...
[20:29:29 INFO]: This server is running Paper version git-Paper-169 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: b4e3b3d)
You are 1 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: git-Paper-164 (MC: 1.20.1)
```

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects
