### ISSUE TITLE
[SUGGESTION] Template system

### ISSUE THREAD

**Issue by oliviathevampire** [oraxen/oraxen#1050]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

I don't think one exists already, might have seen it somewhere, but don't remember where.

A template system which would allow you to have template code which you can use for other blocks/items.

Example:
```yml
template_block:
  template: true
  material: PAPER
  Pack:
    generate_model: true
    parent_model: block/cube_all
  Mechanics:
    noteblock:
      block_sounds:
        place_sound: block.stone.place
        break_sound: block.stone.break
        hit_sound: block.stone.hit
        step_sound: block.stone.step
        fall_sound: my.custom.fallsound
        volume: 0.8
        pitch: 0.8
      hardness: 7
      drop:
        silktouch: true
        fortune: true
        minimal_type: IRON
        best_tools:
        - PICKAXE

arcanite_block:
  variant_of: template_block
  displayname: <#FFFFFF>Arcanite Block
  Pack:
    textures:
    - minerals_pack_v2/arcanite_block
    custom_model_data: 1193
  Mechanics:
    noteblock:
      custom_variation: 98
      model: arcanite_block
      drop:
        loots:
        - oraxen_item: arcanite_block
          probability: 1.0
```

### Reason

Will make it easier to make a lot of blocks with the same settings and would be able to make shorter files without much repetition of properties.
