### ISSUE TITLE
[SUGGESTION] Diagonal Position option for furnitures

### ISSUE THREAD

**Issue by MarkinhosMLP** [oraxen/oraxen#1055]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

a ``diagonal-positioning`` option for furnitures
this could both block or enable diagonal positioning for barrier-furnitures
 (FALSE by default, since some furnitures and their hitboxes could look kinda whacky with it, so it has to be maually set to true)

### Reason

one example = the red glass representing barrier blocks
```yml
      barriers:
      - x: 0
        y: 0
        z: 0
      - x: 1
        y: 0
        z: 0
      - x: 1
        y: 1
        z: 0
      - x: 0
        y: 1
        z: 0
```

![image](https://github.com/oraxen/oraxen/assets/47507632/c85e4c0d-37a5-4b19-baf1-8a3cf3467ff1)
