### ISSUE TITLE
[BUG] Custom Food Effects dont work

### ISSUE THREAD

**Issue by JamesBach93** [oraxen/oraxen#1084]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [x] I have checked if any similar bug reports exist

### Description

On trying to make an own Custom Food the effects dont work.
Even the actions that i want to tell the Player something with it.

In steps to reproduce i paste the Config for it.

### Steps to reproduce

```yml
hamburger:
  displayname: <gradient:#F69D84:#FAD98D>Hamburger
  material: COOKED_BEEF
  Pack:
    generate_model: true
    parent_model: item/generated
    textures:
    - default/hamburger.png
    custom_model_data: 2
  Mechanics:
    food:
      hunger: 20
      effect_probability: 1.0
      effects:
        HEALTH_BOOST:
          amplifier: 1
          duration: 7200
          is_ambient: false
          has_particles: false
          has_icon: true
        SATURATION:
          amplifier: 1
          duration: 7200
          is_ambient: false
          has_particles: false
          has_icon: true
      clickActions:
      - conditions: []
        actions:
          - '[message] <blue>You feel satiated'
```

### Plugin Version

Oraxen version 1.163.0

### ProtocolLib Version

ProtocolLib version 5.1.1-SNAPSHOT-669

### Server Software & Version

git-Purpur-2084 (MC: 1.20.2)

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable
