### ISSUE TITLE
Give command returns null when Items in config have a numerical name

### ISSUE THREAD

**Issue by Classicalad** [oraxen/Oraxen#111]
```
1:
  displayname: "&bZenith Embrace"
  material: NETHERITE_SWORD
  Enchantments:
    sharpness: 6
    looting: 4
    smite: 5
    unbreaking: 3
  lore:
    - ""
    - "&3&m－－－－&b&m－－－－&f&m－－－－&b&m－－－－&3&m－－－－"
    - "&bLegendary Item"
    - "&3&m－－－－&b&m－－－－&f&m－－－－&b&m－－－－&3&m－－－－"
  Pack:
    generate_model: true
    parent_model: "item/handheld"
    textures:
      - legendary_sword.png`
```

The above item shows up perfectly in both /o inv all and its respective /o inv folder in the gui. However if I am to do </o give Classicalad 1 1> it returns an incorrect syntax error, even though chat's tab autofill works correctly.

For compatibility reasons I would really appreciate if this could be resolved, thanks!
