### ISSUE TITLE
Stackable food items consume all at once

### ISSUE THREAD

**Issue by JesseVoncken** [oraxen/oraxen#1145]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

as said, stackable food items seem to all consume at once, in my cause I'm using a Honey Bottle as the item material. they also only give the replacement item back once

### Steps to reproduce

Food Item:
```
beer:
  displayname: <#FFFFFF>Beer
  material: HONEY_BOTTLE
  lore:
  - <#AAAAAA>40% change to get Nausea
  Pack:
    generate_model: true
    parent_model: item/generated
    textures:
    - custom/beer.png
    custom_model_data: 1021
  Mechanics:
    food:
      hunger: 0
      saturation: 0
      replacement:
        oraxen_item: "beer_glass"   
      effect_probability: 1.0           
      effects:
        confusion:                           
          amplifier: 1                   
          duration: 20                    
          is_ambient: true                  
          has_particles: true              
          has_icon: true   
```

replacement Item:
```
beer_glass:
  displayname: <#FFFFFF>Beer Glass
  material: GLASS_BOTTLE
  Pack:
    generate_model: true
    parent_model: item/generated
    textures:
    - custom/beer_glass.png
```

### Plugin Version

Oraxen 1.164.1

### ProtocolLib Version

ProtocolLib 5.1.0

### Server Software & Version

Paper 1.20.1

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects
