### ISSUE TITLE
[BUG] multiple barrier furniture seats are broken

### ISSUE THREAD

**Issue by KlausTrophobie** [oraxen/oraxen#1146]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

On Oraxen 1.163.X and 1.164.X seats from multiple barrier furniture is broken (you can't sit on them anymore).
Furniture that was placed on version <=1.162.0 will continue to work on the new version. Only newly placed furniture with multiple barriers will not work.

### Steps to reproduce

use/place furniture with multiple barriers and seat mechanic

```
summer_furniture_v1_outdoor_sofa:
  displayname: <white>Outdoor Sofa
  material: PAPER
  Mechanics:
    furniture:
      type: DISPLAY_ENTITY
      display_entity_properties:
        width: 0
        height: 0
        display_transform: FIXED
      limited_placing:
        roof: false
        floor: true
        wall: false
      barriers:
      - x: -1
        y: 0
        z: 0
      - x: 0
        y: 0
        z: 0
      - x: 1
        y: 0
        z: 0
      seat:
        height: -0.18
      drop:
        silktouch: false
        loots:
        - oraxen_item: summer_furniture_v1_outdoor_sofa
          probability: 1.0
  Pack:
    generate_model: false
    model: custom/furniture/summer_furniture_v1/outdoor_sofa
    custom_model_data: 1034
```

### Plugin Version

1.163.X + 1.164.X

### Server Software & Version

This server is running Paper version git-Paper-196 (MC: 1.20.1) (Implementing API version 1.20.1-R0.1-SNAPSHOT) (Git: 773dd72)
You are running the latest version
Previous version: git-Paper-297 (MC: 1.20.2)

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable
