### ISSUE TITLE
[SUGGESTION] Something like IA's tool break whitelist and blacklist system

### ISSUE THREAD

**Issue by oliviathevampire** [oraxen/oraxen#1162]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

Ability to do something like 
```yml
break_tools_whitelist:
          - PICKAXE
          - pickaxe
```
 instead of having to individually define each tool

### Reason

Would allow us to do something like 
```yml
andesite_bricks:
  displayname: Andesite Bricks
  material: PAPER
  Pack:
    generate_model: true
    parent_model: block/cube_all
    textures:
    - crystal_creations/vanilla_blocks/andesite_bricks.png
  Mechanics:
    noteblock:
      block_sounds:
        place_sound: block.stone.place
        break_sound: block.stone.break
        hit_sound: block.stone.hit
        step_sound: block.stone.step
        fall_sound: block.stone.fall
        volume: 1.0
        pitch: 1.0
      custom_variation: 10001
      model: andesite_bricks
      hardness: 1.5
      drop:
        silktouch: false
        fortune: false
        minimal_type: IRON
        break_tools_whitelist:
        - PICKAXE
        - pickaxe
        loots:
        - oraxen_item: andesite_bricks
          probability: 1.0
``` 
to more easily allow all types of pickaxes
