### ISSUE TITLE
[SUGGESTION] Add an option for string block type custom blocks to avoid breaking when the block below is removed

### ISSUE THREAD

**Issue by JIMIN0402** [oraxen/oraxen#1210]
### I have checked that...

- [ ] ...such a feature does not exist already
- [ ] ...such a feature request has not been submitted already

### Description

Add an option for string block type custom blocks to avoid breaking when the block below is removed

```
greenhouse_glass:
  displayname: <white>Greenhouse Glass
  material: PAPER
  Mechanics:
    stringblock:
      custom_variation: 4
      model: item/basics/greenhouse_glass
      block_sounds:
        place_sound: block.glass.place
        break_sound: block.glass.break
      drop:
        silktouch: false
        loots:
        - oraxen_item: greenhouse_glass
          probability: 1.0
  Pack:
    generate_model: false
    model: item/basics/greenhouse_glass
    custom_model_data: 1006
```

### Reason

The item cannot be installed in the air.
