### ISSUE TITLE
[SUGGESTION] Support for making new armors using armor trims like Crucible

### ISSUE THREAD

**Issue by oliviathevampire** [oraxen/oraxen#1215]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

This would make a nicer way of doing custom armors, you can choose between shader and armor trim for armors. Example 
```yml
uranium_helmet:
  displayname: Uranium Helmet
  material: CHAINMAIL_HELMET
  Mechanics:
    armor:
      type: ARMOR_TRIM
      texture: hyronic_pack/items/armor/uranium
  Pack:
    custom_model_data: 2
    generate_model: true
    parent_model: item/generated
    textures:
    - hyronic_pack/items/armor/uranium_helmet
    - hyronic_pack/items/armor/uranium_helmet
```

### Reason

Would make allow us to make way more armors and also a bit easier, than having to require the shader + we could technically use other armors.
