### ISSUE TITLE
oraxen_blocks: in limited_placing: doesn't work

### ISSUE THREAD

**Issue by AnatomyKing** [oraxen/oraxen#1249]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

I was creating a banana plant with the stringblock mechanic. I wanted that my banana plant can only be placed on farmland and my custom carotene grass block, which I made using the noteblock mechanic. But it seems like that `limited_placing:` ingnores the `oraxen_blocks:`

### Put these in your Oraxen/items, reload oraxen and try placing the banana plant on the farmland. This should work flawless. now try placing the banana plant on the carotene grass block, this doesn't work.

**Banana Plant Config**
```yml
banana_plant:
  displayname: <white>Banana Seeds
  material: PAPER
  Pack:
    generate_model: false
    model: harambe:item/sprites/banana_seeds
    custom_model_data: 27218
  Mechanics:
    stringblock:
      limited_placing:
        roof: false
        floor: true
        wall: false
        type: ALLOW
        block_types:
          - FARMLAND
        oraxen_blocks:
          - carotene_grass_block
      sapling:
        canGrowNaturally: false # if you want only the player can grow it
        naturalGrowthTime: 600 #in ticks
        canGrowFromBoneMeal: true
        boneMealGrowChance: 50
        growSound: block.weeping_vines.place
        minLightLevel: 4
        requiresWaterSource: false #if you want it to need water
        schematicName: bananatree #structure that will put
      block_sounds:
        place_sound: block.crop.place
        break_sound: block.crop.break
      custom_variation: 18
      model: harambe:decorations/global/banana_plant
      hardness: 2
      drop:
        silktouch: true
        loots:
          - oraxen_item: banana_plant
            probability: 1.0
```
**Carotene Grass Block Config**
```yml
carotene_grass_block:
  displayname: <white>Carotene Grass Block
  material: PAPER
  Pack:
    generate_model: false
    model: harambe:item/block/paradiseland/carotene_grass_block
    custom_model_data: 27220
  Mechanics:
    noteblock:
      block_sounds:
        place_sound: block.grass.place
        break_sound: block.grass.break
        hit_sound: block.grass.hit
        step_sound: block.grass.step
        fall_sound: block.grass.fall
        volume: 0.8
        pitch: 0.8
      custom_variation: 48
      model: harambe:block/paradiseland/carotene_grass_block
      hardness: 4
      drop:
        silktouch: false
        loots:
          - oraxen_item: carotene_grass_block
            probability: 1.0
```

**Example video on how the banana plant behaves**

https://github.com/oraxen/oraxen/assets/128033443/3bf1c282-41a4-4967-8581-fefa2c86ded5

### Plugin Version

```yml
version Oraxen
[15:08:56 INFO]: Oraxen version 1.169.0
[15:08:56 INFO]: Authors: th0rgal and boy0000
```

### ProtocolLib Version

```yml
version ProtocolLib
[15:09:28 INFO]: ProtocolLib version 5.2.0-SNAPSHOT-679
[15:09:28 INFO]: Provides read/write access to the Minecraft protocol.
[15:09:28 INFO]: Authors: dmulloy2 and comphenix
```

### Server Software & Version

```yml
version
[15:10:15 INFO]: Checking version, please wait...
[15:10:15 INFO]: This server is running Paper version git-Paper-424 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 37df121)
You are 2 version(s) behind
Download the new version at: https://papermc.io/downloads/paper
Previous version: git-Paper-405 (MC: 1.20.4)
```

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects
