### ISSUE TITLE
[BUG] <name for bug>

### ISSUE THREAD

**Issue by Tossik99** [oraxen/oraxen#1263]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Tabcomplete doesn't appear for glyphs.. if I type the whole placeholder right, the emoji appears fine, but it can't be tabcompleted.

### Steps to reproduce

paste the emoji textures into oraxen and configure the glyphs as they should be and try typing : in the game and pressing tab.

### Plugin Version

1.170.1

### ProtocolLib Version

5.2-SNAPSHOT-679

### Server Software & Version

Purpur-2127 (1.20.4)

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
```yml
explorer_tag:
  texture: default/chat/explorer_tag
  ascent: 9
  height: 10
  chat:
    tabcomplete: true
    placeholders:
    - ':explorer:'
    permission: oraxen.emoji.explorer
  char: ꐑ
  ```
Works just fine

![image](https://github.com/oraxen/oraxen/assets/62521371/c1cbd0b7-2807-482f-b5f1-327cd0164f13)
