### ISSUE TITLE
[BUG] armor_effects only triggering when removing the armor

### ISSUE THREAD

**Issue by Schroddinger** [oraxen/oraxen#1297]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

The mechanic 'armor_effects' sometimes only triggers when the armor is removed and it only triggers once.
Reloading the plugin (items) helps recreate this.

### Steps to reproduce

1. Create an item with armor effects. This is very noticeable with night_vision.
I've tested this using a hat (PAPER), I'm unaware if this happens with actual armor.
2. Start the server
3. If the bug doesn't happen, try reloading items or the whole plugin `/oraxen reload (items/all)`
4. This is the item I created that currently has this problem, but it also happens with the bundled anubis_head:

```
night_goggles:
  displayname: <gradient:#3948AE:#6699FF>Night vision goggles
  material: PAPER
  AttributeModifiers:
  - attribute: GENERIC_ARMOR
    amount: 2
    operation: 0
    slot: HEAD
    uuid: 0e812cfe-a6f8-47cb-975c-fb7c461c7866
    name: oraxen:modifier
  - attribute: GENERIC_ARMOR_TOUGHNESS
    amount: 1
    operation: 0
    slot: HEAD
    uuid: 6b95e4dd-0ac9-41da-8f11-af63a9106494
    name: oraxen:modifier
  Pack:
    generate_model: false
    model: default/night_goggles # .json extension is not mandatory
    custom_model_data: 1061
  Mechanics:
    hat:
      enabled: true
    armor_effects:
      night_vision:
        amplifier: 0
        duration: 240
        ambient: true # Makes potion effect produce more, translucent, particles.
        particles: false # whether this effect has particles or not
        icon: false # whether this effect has an icon or not
```

### Plugin Version

oraxen-1.171.0

### ProtocolLib Version

ProtocolLib 5.1.0 - 5.1.1

### Server Software & Version

git-Purpur-2153 (MC: 1.20.4)

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable
