### ISSUE TITLE
[BUG] wall + very strict but sideway place

### ISSUE THREAD

**Issue by Nik2810-Original** [oraxen/oraxen#1314]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

So the bug is that you normally should not be able to place it like the furniture if it is limited to wall and restricted_rotation: VERY_STRICT.

### Steps to reproduce

Make a test-texture and put it in textures/custom .Then use this config to create a furniture:
```
test:
  displayname: "<gray>TEST"
  material: PAPER
  Pack:
    generate_model: false
    model: custom/test
  Mechanics:
    furniture:
      restricted_rotation: VERY_STRICT
      limited_placing:
        roof: false
        floor: false
        wall: true
      type: DISPLAY_ENTITY #Valid types are ITEM_FRAME, DISPLAY_ENTITY & GLOWING_ITEM_FRAME
      drop:
        silktouch: false
        loots:
          - { oraxen_item: test, probability: 1.0 }
```
 Now use this item and place it sideways.

### Plugin Version

oraxen-1.171.0

### ProtocolLib Version

v5.2.0-SNAPSHOT-679

### Server Software & Version

Paper 1.20.4

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable
