### ISSUE TITLE
[BUG] Error generating warped_fungus_on_a_stick model

### ISSUE THREAD

**Issue by SrBedrock** [oraxen/oraxen#1315]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

When trying to create a custom item using `warped_fungus_on_a_stick` instead of using parent_model `item/handheld_rod` it uses `item/generated`

### Steps to reproduce

Create a item with `material: WARPED_FUNGUS_ON_A_STICK`

Example:
```yaml
inverno_warped:
  material: WARPED_FUNGUS_ON_A_STICK
  Pack:
    generate_model: true
    textures:
      - inverno/warped
    custom_model_data: 1105
```

or

```yml
inverno_warped:
  material: WARPED_FUNGUS_ON_A_STICK
  Pack:
    generate_model: false
    model: inverno/warped
    textures:
      - inverno/warped
    custom_model_data: 1105
```

JSON created by the plugin:
```json
{
  "parent": "item/generated",
  "textures": { "layer0": "item/warped_fungus_on_a_stick" },
  "overrides": [
    { "predicate": { "custom_model_data": 1105 }, "model": "inverno/warped" }
  ]
}
```

Corret json:
```json
{
  "parent": "item/handheld_rod",
  "textures": { "layer0": "item/warped_fungus_on_a_stick" },
  "overrides": [
    { "predicate": { "custom_model_data": 1105 }, "model": "inverno/warped" }
  ]
}
```

### Plugin Version

 Oraxen version 1.172.0

### ProtocolLib Version

ProtocolLib version 5.2.0-SNAPSHOT-679

### Server Software & Version

Current: git-Purpur-2159 (MC: 1.20.4)

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects
