### ISSUE TITLE
[BUG] Unicode can be used on the anvil

### ISSUE THREAD

**Issue by SrBedrock** [oraxen/oraxen#1316]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

It is possible to rename items using unicode on the anvil, even when the player does not have permission, this includes the oraxen GUI itself.

### Steps to reproduce

1. Use `/lp verbose on <nick> & oraxen`
2. Place an item on the anvil and try renaming it using the unicode defined in the Oraxen configuration like `ꐙ`.
3. No permissions are checked by Oraxen

![image](https://github.com/oraxen/oraxen/assets/51332006/e6f3ff73-0ec2-44db-882a-df3f2410407b)
![image](https://github.com/oraxen/oraxen/assets/51332006/c49bdb26-3758-434c-9980-4481bb75c5e9)

Use default `plugins/Oraxen/glyphs/required.yml` as example:
```yaml
# Simply deleting this file will make the plugin fail to load
# Make sure you delete all entries found in other files
# For example, language file uses logo glyph
logo:
  texture: required/logo
  ascent: 20
  height: 36
  char: ꐙ

menu_banner:
  texture: required/ui/menu_banner
  ascent: -10
  height: 236
  char: ꐚ

menu_recipe:
  texture: required/recipe_showcase
  ascent: 40
  height: 164
  char: ꐛ

menu_items:
  texture: required/ui/menu_items
  ascent: 37
  height: 256
  char: ꐜ

menu_items_overlay:
  texture: required/ui/menu_items_gems
  ascent: 37
  height: 256
  char: ꐝ

recipe_stonecutter:
  texture: required/recipe_stonecutter
  ascent: 40
  height: 164
  char: ꐞ
```

### Plugin Version

Oraxen version 1.172.0

### ProtocolLib Version

ProtocolLib version 5.2.0-SNAPSHOT-679

### Server Software & Version

Current: git-Purpur-2159 (MC: 1.20.4)

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects
