### ISSUE TITLE
[BUG] MiniMessage formatting not parsing correctly for custom items

### ISSUE THREAD

**Issue by ZepsiZola** [oraxen/oraxen#1443]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

I have items that are configured to have bold names. When I do `/o give Zepsi_Zola_ diamond_survivor_sword`, the item does not have a bold name.

### Steps to reproduce

```yaml
diamond_survivor_sword:
  displayname: <gradient:#00aa00:#a3ff98:#00aa00><bold>Survivor's Sword
  material: DIAMOND_SWORD
  Pack:
    generate_model: true
    parent_model: item/handheld
    textures:
    - ve/survivor_swordd.png
    custom_model_data: 1
  Enchantments:
    looting: 4
    sharpness: 5
    sweeping: 3
    unbreaking: 5
```

![image](https://github.com/oraxen/oraxen/assets/49735083/163439e8-9964-4f52-b8d1-0251d9ec475a)

### Plugin Version

1.177.0

### ProtocolLib Version

5.2.1-SNAPSHOT-689

### Server Software & Version

This server is running Pufferfish+ version git-PufferfishPlus-45 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: eb69634 on HEAD)

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable
