### ISSUE TITLE
[SUGGESTION] Item plugin hooks

### ISSUE THREAD

**Issue by kristophergeou** [oraxen/oraxen#1507]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

This suggestion aims to add compatibility between [ExecutableItems](https://www.spigotmc.org/resources/custom-items-plugin-executable-items.77578/) and [ExecutableBlocks](https://www.spigotmc.org/resources/custom-blocks-plugin-executable-blocks.93406/) with oraxen's items. Specifically oraxen's items will directly hook into the corresponding ExecutableItems/Blocks based on the item's id. As a result, the item from oraxen will have the material, name, lore, and NBT data from the ExecutableItem or ExecutableBlock plugins.

_(The following example could be used as a reference of how these items will look config-wise)_
**For ExecutableItems:**
```yml
example_executableitems:
  displayname: "<gradient:#59A7EA:#F1D2FF>EI Test"
  executableitems:
    id: my_executableitem_id
```

**For ExecutableBlocks:**
```yml
example_executableblocks:
  displayname: "<gradient:#59A7EA:#F1D2FF>EB Test"
  executableblocks:
    id: my_executableblock_id
```

## Plugins API
For ExecutableItems > https://docs.ssomar.com/executableitems/developer-api
For ExecutableBlocks > https://docs.ssomar.com/executableblocks/developer-api

### Reason

It would be a great enhancement for oraxen to support more direct hooks with other item plugins, allowing for greater customization options for the users.
