### ISSUE TITLE
[BUG] Trees from the Sapling Mechanic don't grow naturally.

### ISSUE THREAD

**Issue by Aleksander3453** [oraxen/oraxen#1539]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

I made a config for a custom sapling in Oraxen. The tree grows successfully from bone meal, but no matter how much I set the naturalGrowthTime variable (with canGrowNaturally: true of course), the tree never grows on its own.

```
darkwood_sapling:
  itemname: <white>Darkwood Sapling
  material: GRASS
  Pack:
    generate_model: false
    model: default/darkwood_sapling
    custom_model_data: 1
  Mechanics:
    stringblock:
      sapling:
        canGrowNaturally: true
        naturalGrowthTime: 600 #in ticks
        canGrowFromBoneMeal: true
        boneMealGrowChance: 30
        growSound: block.grass.break
        minLightLevel: 0
        requiresWaterSource: false
        schematicName: darkwood_tree_3
        shouldReplaceBlocks: true
      custom_variation: 1
      model: default/darkwood_sapling
      hardness: 2
      drop:
        silktouch: false
        loots:
          - { oraxen_item: darkwood_sapling, probability: 1.0 }
```

### Steps to reproduce

1. Make a custom sapling using the docs (https://docs.oraxen.com/mechanics/stringblock-mechanic/sapling-mechanic)
2. Make sure the sapling has at least canGrowNaturally set to true
3. Do /oraxen reload all
4. Get the sapling from the /oraxen inventory
5. Place it on grass and wait for the ticks defined in the saplings' naturalGrowthTime
6. The tree never grows over time no matter what, but try to use bone meal on the sapling, the tree should finally appear.

### Plugin Version

[11:00:29 INFO]: Oraxen version 1.182.0
[11:00:29 INFO]: Authors: th0rgal and boy0000

### ProtocolLib Version

[11:00:50 INFO]: ProtocolLib version 5.3.0-SNAPSHOT-732
[11:00:50 INFO]: Provides read/write access to the Minecraft protocol.
[11:00:50 INFO]: Authors: dmulloy2 and comphenix

### Server Software & Version

[11:01:04 INFO]: This server is running Paper version 1.21.1-105-master@b7ab22d (2024-09-27T18:16:58Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable
