### ISSUE TITLE
[BUG] Tags don't work for recipes

### ISSUE THREAD

**Issue by WaxenSs** [oraxen/oraxen#1545]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

put a `tag` in one of the recipe files instead of a `minecraft_type`

### Steps to reproduce

example:
```
wooden_hammer:
  result:
    oraxen_item: wooden_hammer
  ingredients:
    A:
      minecraft_tags: logs
    B:
      minecraft_type: STICK
  shape:
  - AAA
  - AAA
  - _B_
```
the result is _(even after a server restart)_:
![CleanShot 2024-10-14 at 15 58 53](https://github.com/user-attachments/assets/d91d1fda-fbe7-4727-bb3d-484729ca26d9)

I tested with:
```
minecraft_tags: minecraft:logs
minecraft_tags: logs
tags: minecraft:logs
tags: minecraft:logs
```

### Plugin Version

oraxen-1.182.0

### ProtocolLib Version

ProtocolLib v5.3.0-SNAPSHOT-732

### Server Software & Version

paper-1.21.1-119

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable
