### ISSUE TITLE
[BUG] PersistentData not working

### ISSUE THREAD

**Issue by SpaceboiX** [oraxen/oraxen#1565]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

PersistentData is not working on Oraxen-2.0-SNAPSHOT
Trying to add NBT to an item, doesn't work

Tested via broadcasting the NBT to the console

### Steps to reproduce

```
ruby_block:
  displayname: Ruby Block
  material: CLOCK
  Pack:
    generate_model: true
    parent_model: block/cube_all
    texture: minecraft:block/ruby_block
    custom_model_data: 1
  PersistentData:
  - key: oraxen:mydata
    type: BOOLEAN
    value: true
```

### Plugin Version

Oraxen version 2.0-SNAPSHOT

### ProtocolLib Version

ProtocolLib version 5.3.0

### Server Software & Version

Current Purpur Version: 1.21.1-2329-803bf62 (MC: 1.21.1)

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable
