### ISSUE TITLE
[BUG] silktouch: false doesn't disable silktouch

### ISSUE THREAD

**Issue by Quik2007** [oraxen/oraxen#1633]
### I have checked...

- [x] I am using the latest version of Oraxen
- [x] I am using the latest version of any dependencies
- [x] I am using ProtocolLib 5.0+
- [x] I have checked if any similar bug reports exist

### Description

This is very low priority. If one creates a custom block with the silktouch mechanic set to false (meaning no silktouch necessary), the `false` is ignored and silktouch is still required.

(Low priority because not needing silktouch is default behavior and `silktouch: false` is completely unnecessary)

### Steps to reproduce

```
my_block:
  itemname: My block
  material: DIAMOND_BLOCK
  Pack:
    generate_model: true
    parent_model: block/cube_all
  Mechanics:
    noteblock:
      custom_variation: 2
      drop:
        silktouch: true 
        best_tools:
          - PICKAXE
```
works like expected

```
my_block:
  itemname: My block
  material: DIAMOND_BLOCK
  Pack:
    generate_model: true
    parent_model: block/cube_all
  Mechanics:
    noteblock:
      custom_variation: 2
      drop:
        silktouch: false 
        best_tools:
          - PICKAXE
```
silktouch: false does not actually disable the need for silktouch

### System Report
**Plugin Versions:**
- Oraxen: 1.189.0
- ProtocolLib: 5.3.0

**Server Information:**
- Software: Paper
- Version: 1.21.4-224-0cf7315 (MC: 1.21.4)

**System Information:**
- OS: Linux
- OS Version: 6.13.9-200.fc41.x86_64
- Architecture: amd64

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects
