### ISSUE TITLE
A few problems and a request for help

### ISSUE THREAD

**Issue by matyasvane** [oraxen/oraxen#248]
**PAID from Spigot**

I wrote on the discord support, but I'm not sure if anyone read my messages.

**I.**
Can I somehow set the effect when laying a block? I have a problem that some of the items I put are without the effect of waving my hand. For example, when a player places a vanilla item.

**II.**

The plugin rewrites certain blocks for me after restarting or adding new items to the resource pack. But maybe I misunderstood adding new items.

1. I will write everything in items.yml
2. I will add all the textures and possibly write json
3. I will write / o reload all
4. Then restart the server

(The problem is that if I do not restart the server and start using the objects and only then restart the plugin, all the placed blocks will be destroyed). I do not understand why.

**III.**

Can i use multiple songs for one? Like YES by Villager.. i using any new mobs..

```
  ambient:
    category: hostile
    sound: 
    - custom/mobs/sonbi/sonbiambient1
    - custom/mobs/sonbi/sonbiambient2
    - custom/mobs/sonbi/sonbiambient3
    - custom/mobs/sonbi/sonbiambient4
```
