### ISSUE TITLE
[Bug Report] amount set is not working

### ISSUE THREAD

**Issue by wdfeww** [oraxen/oraxen#252]
Hello, I am creating a new recipe. I have set each resource the amount that should be required for creating an item via gui in-game, but it looks like it is not working as expected
I have used the command `/o recipes builder shaped`
![image](https://user-images.githubusercontent.com/22939457/140801769-9219a957-ff38-4824-ae6e-fe44fa05c0c1.png)
then I saved the recipe `/o recipes save emerald_hammer` and then I restarted the server

problem is that the crafting table creates the item with the wrong amount of resources set
![image](https://user-images.githubusercontent.com/22939457/140802110-d3759910-2fd5-4999-93a7-917a57a4ddba.png)

`/o recipes show emerald_hammer`
![image](https://user-images.githubusercontent.com/22939457/140802217-991a35d5-83f3-4fae-b25f-abf04d3c51f3.png)

generated file => `shaped.yml`
```
emerald_hammer:
  result:
    oraxen_item: emerald_hammer
  ingredients:
    B:
      minecraft_item:
        ==: org.bukkit.inventory.ItemStack
        v: 2730
        type: STICK
        amount: 2
    A:
      minecraft_item:
        ==: org.bukkit.inventory.ItemStack
        v: 2730
        type: EMERALD_BLOCK
        amount: 3
  shape:
  - AAA
  - _B_
  - _B_
```
  
  
  Did I do something wrong or this is a real issue?
  
server version: spigot 1.17.1 on Ubuntu 21.10
oraxen version: oraxen-1.118.1-all
java: 17.0.1 2021-10-19 LTS
