### ISSUE TITLE
[BUG!] 2D Texture not working when material can placable like TRIPWIRE_HOOK or STAINED_GLASS_PANE

### ISSUE THREAD

**Issue by ArtifactyNight** [oraxen/oraxen#291]
Material which have 2D Texture and can place too like TRIPWIRE_HOOK, STAINED_GLASS_PANE, LANTERN, or Any Flowers
can't add texture

example: 
```yml
key_copper:
  displayname: Key Copper
  material: TRIPWIRE_HOOK # <--- This is 2D Display texture and can placable item
  Pack:
    generate_model: true
    custom_model_data: 101
    parent_model: item/generated
    textures:
    - custom/items/keys/copper.png
```

result:
![image](https://user-images.githubusercontent.com/53427253/154982999-a95a143d-65a6-40f4-b784-aa871b9ea538.png)
