### ISSUE TITLE
Towny protection issue

### ISSUE THREAD

**Issue by Fer-Jgu** [oraxen/oraxen#311]
When using the thor mechanic the user can turn villagers into witches (and I guess any other entity with this thunder-transformation mechanic) inside a town (which should not be possible because of the protection the town provides).
Here's the config for the weapon causing this:
```yaml
espada_electrica:
  displayname: "<gradient:#3685EC:#72C1E4>Espada Electrica"
  material: IRON_SWORD
  AttributeModifiers:
    - {name: "oraxen", attribute: GENERIC_ATTACK_DAMAGE, amount: 6, operation: 0, uuid: d1fe3908-8aa8-49bb-8c1f-907b765a43ab, slot: HAND}
    - {name: "oraxen", attribute: GENERIC_ATTACK_SPEED, amount: 1.4, operation: 0, uuid: 35f224b1-bd48-4ca1-bd0e-bbb760b2aa0c, slot: HAND}
  lore:
    - "<#6f737d>» <#D5D6D8>Click Derecho para invocar a los rayos"
  Pack:
    generate_model: true
    parent_model: "item/handheld"
    textures:
      - default/espada_electrica.png
  Mechanics:
    thor:
      lightning_bolts_amount: 5
      random_location_variation: 2
      delay: 10000
```

Oraxen version 1.130.0
Server version: git-Purpur-1445 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT)
Towny version 0.97.5.0
