### ISSUE TITLE
[SUGGESTION] Random Place Feature

### ISSUE THREAD

**Issue by lucian929** [oraxen/oraxen#361]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

Pretty simple request, I think it'd be great if for things like the tripwire mechanic, we could have a random place submechanic:

```yaml
  Mechanics:
    stringblock:
      randomplace:
        - stones_1
        - stones_2
        - stones_3
  ```
  
  Basically, it would just choose one of the stones out of this list to place instead of giving your players 3 different stones.

### Reason

QOL
