### ISSUE TITLE
[SUGGESTION] Item properties

### ISSUE THREAD

**Issue by EspartaProJunior** [oraxen/oraxen#363]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

Type of item

It would be good to add a mechanism to specify the type of item that with that mechanism you can add a specific item that can make an option such as breaking a block faster, example of item

```
epic_drill:
  displayname: "<white>Epic drill"
  material: DIAMOND
  properties:
    type: DRILL
  Pack:
    generate_model: true
    parent_model: "item/handlend"
    textures:
      - default/epic_drill
 ```

block example

```
epic_stone:
  displayname: "<white>epic_stone"
  material: PAPER
  lore:
    - "<gray>→ Item <white>"
    - "<gray>→ Type <gold>Block"
  Pack:
    generate_model: false # because this is a block, a 2nd model pointing to specified one will be generated anyway
    model: custom/blocks/epic_stone
    custom_model_data: 338
  Mechanics:
    noteblock:
      custom_variation: 69
      model: custom/blocks/epic_stone
      hardness: 6
      drop:
        minimal_type: STONE
        silktouch: false 
        best_tools:
          - DRILL
        loots:
          - { oraxen_item: epic_stone, probability: 1.0 }
```

permissions to use a specific item

```
epic_sword:
  displayname: "<white>Epic Sword"
  material: IRON_SWORD
  properties:
    type: SWORD
    permission: "custom.item.epic_sword"
    permission_craft: "custom.item.epic_sword" #and also this permission either to be able to craft the item
  Pack:
    generate_model: true
    parent_model: "item/handlend"
    textures:
      - default/epic_sword
```

better sound system when placing blocks

```
steel_block:
  displayname: "<white>Steel Block"
  material: PAPER
  lore:
    - "<gray>→ Item <white>"
    - "<gray>→ Type <gold>Block"
  Pack:
    generate_model: true
    parent_model: "block/cube_all"
    textures:
      - custom/default/steel_block
    custom_model_data: 213
  Mechanics:
    noteblock:
      custom_variation: 8
      model: steel_block
      hardness: 5
      sounds:
        break: { sound: block.stone.break, volume: 1, pitch 0.8 }
        place { sound: block.stone.place, volume: 1, pitch 0.8 }
      drop:
        silktouch: false 
        minimal_type: STONE
        loots:
          - { oraxen_item: steel_block, probability: 1.0 }
```

and also when consuming custom items

```
cabagge_plant:
  displayname: "<gradient:#46EEAA:#2CBFC7>cabagge"
  material: COOKED_BEEF
  Mechanics:
    sounds:
      use: { sound: custom.use, volume: 1, pitch 1 } #by eating the object
      interact { sound: custom.zombie.attack, volume: 1, pitch 1 }  #when attacking or interacting with the blocks
  lore:
    - "<gray>→ Item <white>"
    - "<gray>→ Type <gold>Plant"
  Pack:
    generate_model: false
    model: custom/plants/cabagge
    custom_model_data: 56
 ```

It would also be nice if when you click on this block or stringblock and noteblock you could switch to another oraxen item, e.g.

```
stones:
  displayname: "<gray>Stones"
  material: PAPER
  lore:
    - "<gray>→ Item <white>"
    - "<gray>→ Type <gold>Furtniture"
  Pack:
    generate_model: false
    model: custom/furniture/piedras_1
    custom_model_data: 309
  Mechanics:
    stringblock:
      custom_variation: 1
      model: custom/furniture/piedras
      hardness: 2
      interact:
       switch: stones_2
      drop:
        silktouch: false
        loots:
          - { oraxen_item: stones, probability: 1.0 }
          
stones_2:
  displayname: "<gray>Stones"
  material: PAPER
  lore:
    - "<gray>→ Item <white>"
    - "<gray>→ Type <gold>Furtniture"
  Pack:
    generate_model: false
    model: custom/furniture/piedras_2
    custom_model_data: 309
  Mechanics:
    stringblock:
      custom_variation: 2
      model: custom/furniture/piedras_2
      hardness: 2
      interact:
       switch: stones
       drop: stones
      drop:
        silktouch: false
        loots:
          - { oraxen_item: stones_2, probability: 1.0 }
 ```

https://imgur.com/a/Jopw6Ga

### Reason

Increased item customization either to add better functionality or interaction of the item
