### ISSUE TITLE
1

### ISSUE THREAD

**Issue by pacificminer** [oraxen/oraxen#365]
1

**Comment by Boy0000** [comment]
The default configs should have been fixed.
Please share the configs used if you dont mind @pacificminer

**Comment by pacificminer** [comment]
> The default configs should have been fixed. Please share the configs used if you dont mind @pacificminer

`weed_leaf:
  displayname: "<gradient:#46EEAA:#2CBFC7>Athelas Leaf"
  material: COOKED_BEEF
  Pack:
    generate_model: true
    parent_model: "item/generated"
    textures:
      - default/weed/leaf
  Mechanics:
    consumablepotioneffects:
      confusion:
        amplifier: 0
        ambient: true # Makes potion effect produce more, translucent, particles.
        particles: true # whether this effect has particles or not
        icon: true # whether this effect has an icon or not
        duration: 200 # 10 seconds in ticks
      speed:
        amplifier: 0
        ambient: true # Makes potion effect produce more, translucent, particles.
        particles: true # whether this effect has particles or not
        icon: true # whether this effect has an icon or not
        duration: 6000 # 5 minutes
      saturation:
        amplifier: 1
        ambient: true # Makes potion effect produce more, translucent, particles.
        particles: true # whether this effect has particles or not
        icon: true # whether this effect has an icon or not
        duration: 6000 # 5 minutes
      levitation:
        amplifier: 0
        ambient: true # Makes potion effect produce more, translucent, particles.
        particles: true # whether this effect has particles or not
        icon: true # whether this effect has an icon or not
        duration: 5 # 5 ticks

weed_seed:
  displayname: "<gradient:#46EEAA:#2CBFC7>Athelas Seed"
  material: PAPER
  Mechanics:
    furniture:
      item: weed_plant_stage0
      facing: UP
      barrier: false
      farmland_required: true
      evolution:
        delay: 10000
        probability: 0.5
        light_boost: true
        next_stage: weed_plant_stage1
      drop:
        silktouch: true
        loots:
          - { oraxen_item: weed_seed, probability: 1.0 }
  Pack:
    generate_model: true
    parent_model: "item/generated"
    textures:
      - default/weed/seed

weed_plant_stage0:
  material: PAPER
  excludeFromInventory: true
  Pack:
    generate_model: false
    model: default/weed/stage0

weed_plant_stage1:
  material: PAPER
  excludeFromInventory: true
  Mechanics:
    furniture:
      facing: UP
      barrier: false
      farmland_required: true
      evolution:
        delay: 10000
        probability: 0.5
        light_boost: true
        next_stage: weed_plant_stage2
      drop:
        silktouch: true
        loots:
          - { oraxen_item: weed_seed, probability: 1.0 }
  Pack:
    generate_model: false
    model: default/weed/stage1

weed_plant_stage2:
  material: PAPER
  excludeFromInventory: true
  Mechanics:
    furniture:
      facing: UP
      barrier: false
      farmland_required: true
      evolution:
        delay: 10000
        probability: 0.5
        light_boost: true
        next_stage: weed_plant_stage3
      drop:
        silktouch: true
        loots:
          - { oraxen_item: weed_seed, probability: 1.0 }
  Pack:
    generate_model: false
    model: default/weed/stage2

weed_plant_stage3:
  material: PAPER
  excludeFromInventory: true
  Mechanics:
    furniture:
      facing: UP
      barrier: false
      farmland_required: true
      drop:
        silktouch: true
        loots:
          - { oraxen_item: weed_seed, max_amount: 2, probability: 0.75 }
          - { oraxen_item: weed_leaf, max_amount: 5, probability: 0.55 }
  Pack:
    generate_model: false
    model: default/weed/stage3`

**Comment by Boy0000** [comment]
The last stage is missing the evolution mechanic.
As mentioned its fixed in the default config, tho iguess it wouldnt overwrite yours.¨
Simply copy paste the evolution mechanic from the previous stage, and remove `next_stage:` to have it work 👍  @pacificminer 

```
weed_plant_stage3:
  material: PAPER
  excludeFromInventory: true
  Mechanics:
    furniture:
      facing: UP
      barrier: false
      farmland_required: true
      evolution:
        delay: 10000
        probability: 0.5
        light_boost: true
      drop:
        silktouch: true
        loots:
          - { oraxen_item: weed_seed, max_amount: 2, probability: 0.75 }
          - { oraxen_item: weed_leaf, max_amount: 5, probability: 0.55 }
  Pack:
    generate_model: false
    model: default/weed/stage3
```
