### ISSUE TITLE
[BUG] Furnace

### ISSUE THREAD

**Issue by Domzzo** [oraxen/oraxen#435]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I have checked if any similar bug reports exist

### Description

When using custom textured food, cooking it outputs normal item even when custom texture is set and normally works.

### Steps to reproduce

**Item Config:**

venison_cooked:
  displayname: "<white>Venison Cooked"
  material: COOKED_PORKCHOP
  Pack:
    generate_model: false
    model: food/land/venison_cooked
    custom_model_data: 70002
    
venison:
  displayname: "<white>Venison"
  material: PORKCHOP
  Pack:
    generate_model: false
    model: food/land/venison
    custom_model_data: 70003
    
    
**Furnace Config**
venison_cooked1:
  experience: 200
  cookingTime: 200
  result:
    oraxen_item: venison_cooked
  input:
    oraxen_item: venison

### Plugin Version

[11:13:20 INFO]: Oraxen version 1.139.0
[11:13:20 INFO]: Author: Th0rgal

### ProtocolLib Version

[11:13:50 INFO]: ProtocolLib version 5.0.0-SNAPSHOT-b587
[11:13:50 INFO]: Provides read/write access to the Minecraft protocol.
[11:13:50 INFO]: Authors: dmulloy2 and comphenix

### Server Version

[11:14:03 INFO]: This server is running Paper version git-Paper-111 (MC: 1.19.1) (Implementing API version 1.19.1-R0.1-SNAPSHOT) (Git: 02831e3)

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment]
tried this just now and cant reproduce it. Please double check that your players have the recipe in question unlocked and permission for it @Domzzo 
![image](https://user-images.githubusercontent.com/62521371/184511404-f002c089-ea8b-455e-98ee-2dce4663527f.png)

ofcourse different textures as i have my own resourcepack but.

item configs:
```yml
venison_cooked:
  displayname: "Venison Cooked"
  material: COOKED_PORKCHOP
  Pack:
    generate_model: false
    model: food/land/venison_cooked
    custom_model_data: 70002

venison:
  displayname: "Venison"
  material: PORKCHOP
  Pack:
    generate_model: false
    model: food/land/venison
    custom_model_data: 70003
```

Furnace recipe:
```yml
venison:
  experience: 200
  cookingTime: 200
  result:
    oraxen_item: venison_cooked
  input:
    oraxen_item: venison
```
