### ISSUE TITLE
Drop Event Doesn't Trigger Custom Mechanic

### ISSUE THREAD

**Issue by MillionthOdin16** [oraxen/oraxen#447]
I have a custom mechanic that triggers a console command when an item is picked up. The pickup and click events trigger my custom mechanic fine, but I can't get my custom mechanic, or any of the other example items with custom mechanics, to fire on the item drop Event.

My custom item entry in items.yml is below:
```
wildlands_permit:
  displayname: <gradient:#3685EC:#72C1E4>Wildlands Permit
  material: PAPER
  lore:
  - <#6f737d>» <#D5D6D8>Carry this license in your inventory
  - '   <#D5D6D8>to use the Wildlands Portal'
  - '<#6f737d>» <gradient:#3685EC:#72C1E4>Drop+Pickup to load Resource Pack'
  Pack:
    generate_model: true
    parent_model: item/generated
    textures:
    - default/wildlands_license.png
    custom_model_data: 41
  Mechanics:
    custom:
      GivePerm:
        one_usage: false
        event: PICKUP
        conditions:
          - '#player.hasPermission("group.default")'
        actions:
          - "[console] o pack send <player>"
          - "[console] lp user <player> permission set multiverse.access.wildlands true"
    custom1:
      GiveClickPerm:
        one_usage: false
        event: CLICK:all:all
        conditions:
          - '#player.hasPermission("group.default")'
        actions:
          - "[console] o pack send <player>"
          - "[console] lp user <player> permission set multiverse.access.wildlands true"
    custom2:
      TakePerm:
        one_usage: false
        event: DROP
        conditions:
          - '#player.hasPermission("group.default")'
        actions:
          - ""
          - "[console] lp user <player> permission unset multiverse.access.wildlands"
```
*edited to include code block
