### ISSUE TITLE
[BUG] Sound Mechanic: Sound accelerated / cut off

### ISSUE THREAD

**Issue by SFlakeZ** [oraxen/oraxen#530]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I have checked if any similar bug reports exist

### Description

I am using the latest Oraxen version with the updated/new sound mechanic.
The vanilla stone and wooden blocks sound great, but with the custom blocks it sounds
accelerated / cut off.

**Short video example can be found here:**
https://www.youtube.com/watch?v=vPTfsuD2Bnw&feature=youtu.be
At `0:32` you can see that I hold `left_mouse_button` and the sound was normal on the custom block.

**_mechanics.yml_**
```yaml
# Specify if custom block sounds should be enabled for the below mechanics
# If both mechanics are disabled, this will force the sound system for those off
custom_block_sounds:
  noteblock_and_block: true
  stringblock_and_furniture: true
```

**_blocks.yml_**
```yaml
  Mechanics:
    noteblock:
      block_sounds:
        break_sound: required.stone.break
        place_sound: required.stone.place
        hit_sound: required.stone.hit
        step_sound: required.stone.step
        fall_sound: required.stone.fall
        volume: 0.8 # default: 0.8
        pitch: 0.8 # default: 0.8
```

### Steps to reproduce

1 - `Install latest Oraxen`
2 - `Activate/add custom_block_sounds in mechanics.yml`
3 - `Add block_sounds mechanic to desired furniture/noteblock`

### Plugin Version

```go
Oraxen version 1.144.0
Author: Th0rgal
```

### ProtocolLib Version

```go
ProtocolLib version 5.0.0-SNAPSHOT-b600
Provides read/write access to the Minecraft protocol.
Authors: dmulloy2 and comphenix
```

### Server Version

```go
This server is running Paper version git-Paper-220 (MC: 1.19.2)
(Implementing API version 1.19.2-R0.1-SNAPSHOT) (Git: 3dcfec4)
You are running the latest version
Previous version: git-Paper-219 (MC: 1.19.2)
```

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects
