### ISSUE TITLE
[BUG] JUKEBOX volume 

### ISSUE THREAD

**Issue by mani1232** [oraxen/oraxen#540]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I have checked if any similar bug reports exist

### Description

I want to create my own JUKEBOX with increased volume of records, but the volume does not change

### Steps to reproduce

```
newplayer:
  displayname: "<aqua>NEW JUKEBOX</aqua>"
  lore:
    - "<gray></gray>"
  material: JUKEBOX
  Mechanics:
    furniture:
      jukebox:
        volume: 100.0
        pitch: 100.0
        permission: ""
```

### Plugin Version

1.145.0

### ProtocolLib Version

ProtocolLib build 602
https://ci.dmulloy2.net/job/ProtocolLib/

### Server Version

Purpur 1.19.2

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects
