### ISSUE TITLE
[Bug] block.sound/wood is not replaced internally for Custom Block Sound check

### ISSUE THREAD

**Issue by Yukylyu** [oraxen/oraxen#598]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Hi,
I have a problems since the last version despite the application on the configuration, there is a problem with the sounds.
For example
noteblock:
block_sounds:
break_sound: block.stone.break
place_sound: block.stone.place
The sounds block.stone.break & block.wood.break not working making no sound unlike the other.
Thanking you in advance for your help.

### Steps to reproduce

- Place a block
- Break the block

### Plugin Version

oraxen-1.148.2

### ProtocolLib Version

ProtocolLib v5.0.0-SNAPSHOT-b600

### Server Software & Version

paper-1.19.2-138

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by Boy0000** [comment]
Known bug, as it should replace them
In the meantime just use required.stone.break and required.wood @Yukylyu

**Comment by Boy0000** [comment]
@Yukylyu I am unable to replicate this at all. Please make sure say block.wool.place works
this is my config and it works just fine:
```yml
Mechanics:
    noteblock:
      block_sounds:
        break_sound: block.wood.break
        place_sound: block.wood.place
        hit_sound: block.wood.hit
        step_sound: block.wood.step
 ```
