### ISSUE TITLE
ADD SUGAR_CANE BLOCKDATA!

### ISSUE THREAD

**Issue by bckd00r** [oraxen/oraxen#607]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

I support the new version of Oraxen and I think it should improve. I have already edited some minor mistakes myself, but I thought that sugar canes should be added as block data. Sugar canes have a total of 16 (Ageable) data and they are almost useless. Block sugarcane from changing with a block physics event (it does not prevent it from growing) ) so we can create "sugarblock:" and make plants and saplings from them.

```
sugarblock:
  displayname: "<#f5ec42>CustomSugarBlock"
  material: PAPER
  Pack:
    generate_model: true
    parent_model: "item/generated"
    textures:
      - custom/misc_items/sugarblock.png # 
  Mechanics:
    sugarblock:
      custom_variation: 1 #(1 to 15)
      model: custom/plants/sugarblock
      drop:
        silktouch: false
        loots:
          - { oraxen_item: sugarblock, probability: 1.0 }
```

### Reason

When I examined the Oraxen codes, I realized that you made some things too many functions, which made me very happy, but for such simple blocks, the functional properties of "hardness", "customsound" and note blocks are not desired. I can send you the changes I made for sugar_cane blocks if you write to me on discord. Adding such functionality to the plugin would make a huge difference to competing plugins.
