### ISSUE TITLE
[BUG] Glyphs not working on 1.19.3

### ISSUE THREAD

**Issue by SubGplayz** [oraxen/oraxen#612]
### I have checked...

- [x] I am using the latest version of Oraxen
- [x] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

whenever using the pack on 1.19.3, only one glyph displays correctly, and all other glyphs appear as if they had not been changed. When testing on 1.19.2, they all work however. All of the glyph configs appear to be correct since it works on one version but not the other, and it may be an issue with the pack conversion on 1.18.2 servers, but I am not too sure.

### Steps to reproduce

Not sure if this will reproduce, but what I did was create a 1.19.2 server, add all of my glyphs (with their codes set), and connect to the server using 1.19.3 through viaversion. This was all without a proxy.

### Plugin Version

1.149.1

### ProtocolLib Version

5.0.0-SNAPSHOT-b602

### Server Software & Version

![image](https://user-images.githubusercontent.com/68687751/209847565-a6cd5ff9-cc96-4391-8824-051296109ca3.png)

using viaversion to join with 1.19.3

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

### Configs
Settings.yml:
```
Plugin:
  language: english
  commands:
    repair:
      oraxen_durability_only: false # will not repair vanilla items if set to true
    emoji_list:
      only_show_emojis_with_permission: true # will only show emojis player has permission to use if set to true
  generation:
    default_assets: true
    default_configs: true
  worldedit: # Please note these are both experimental still and should be used with caution
    noteblock_mechanic: false
    stringblock_mechanic: false # Works, but is buggy with some stringblocks, specifically with Tall-property
  experimental:
    convert_pack_for_1_19_3: true # Temporary automatic conversion for new 1.19.3 pack format

Pack:
  generation:
    generate: true # Unlike Plugin.generation.default_assets, this will enable/disable all pack generation
    # 64x32 layer is default size and corresponds to 16. If you need higher
    # resolution, e.g. 128x64, you should set this parameter to 32 and so on.
    armor_resolution: 16
    automatically_generate_shader_compatible_armor: true
    compression: BEST_COMPRESSION # see Deflater.class
    # protection will use several methods to make your pack impossible to extract
    # with usual tools (native windows unzip, 7zip, winrar, etc) without altering
    # its integrity. Be careful if you activate this option to not try to extract
    # the pack or you might fill your disk.
    protection: true
    comment: |-
      The content of this texture pack
      belongs to the owner of the Oraxen
      plugin and any complete or partial
      use must comply with the terms and
      conditions of Oraxen.
    attempt_to_migrate_duplicates: false
    animated_armor_framerate: 24
  
  upload:
    enabled: true
    type: polymath # transfer.sh or polymath
    polymath:
      server: atlas.oraxen.com # you can also host your own polymath instance
  
  dispatch:
    send_pack: true
    delay: -1
    # this option requires ProtocolLib and will make the pack loading more fluid
    send_pack_advanced:
      enabled: true
      mandatory: true
      message: <#fa4943>Accept the pack to enjoy a full <b><gradient:#9055FF:#13E2DA>Oraxen</b><#fa4943>
        experience
    join_message:
      enabled: false
      delay: -1
    send_on_reload: true
  
  receive:
    enabled: true
    
    loaded:
      actions:
        sound:
          # Disabled by default, just switch to enabled to send
          # the below sound whenever someone joins
          enabled: false
          type: minecraft:welcome
          volume: 1.0
          pitch: 1.0
        delay: 5 # delay in ticks
        message:
          enabled: false
          # KICK / CHAT / ACTION_BAR / TITLE
          type: ACTION_BAR
          # Click and Hover elements are only available by using the CHAT type
          content: <#55ffa4><bold>ResourcePack loaded
        # If you need to send commands
        commands:
          console: []
          player: []
          opped_player: []
    
    accepted:
      actions:
        message:
          # KICK / CHAT / ACTION_BAR / TITLE
          type: ACTION_BAR
          # Click and Hover elements are only available by using the CHAT type
          content: <#55ffa4><bold>ResourcePack accepted
        # If you need to send commands
        commands:
          console: []
          player: []
          opped_player: []
    
    denied:
      actions:
        message:
          enabled: false
          # KICK / CHAT / ACTION_BAR / TITLE
          type: CHAT
          # Click and Hover elements are only available by using the CHAT type
          content: <red>You refused the ResourcePack, but you need it in order to
            see the new items. Please </red><click:run_command:'/oraxen pack send
            @p'><hover:show_text:'<green>Display more informations'><green><bold>CLICK
            HERE</bold></hover></click> <red>or type <bold>/oraxen pack send @p
        # If you need to send commands
        commands:
          console: []
          player: []
          opped_player: []
    
    failed_download:
      actions:
        message:
          enabled: false
          # KICK / CHAT / ACTION_BAR / TITLE
          type: CHAT
          # Click and Hover elements are only available by using the CHAT type
          content: <red>You failed to download the ResourcePack, but you need it in
            order to see the new items. Please </red><click:run_command:'/oraxen pack
            send @p'><hover:show_text:'<red>! loading the resourcepack from the game
            can cause lags'><red><bold>CLICK HERE</bold></hover></click> <red>to retry
            or type <bold>/oraxen pack send @p</bold>
        # If you need to send commands
        commands:
          console: []
          player: []
          opped_player: []

ConfigsTools:
  # Nice for production servers, automatically set model data in settings so
  # that you can add new items without breaking existing ones
  automatically_set_model_data: false
  # list of model data numbers the automatic system will skip
  # List can take ranges like 1-4 as well as normal singular numbers
  skipped_model_data_numbers: []
  # Same option for glyph codes
  automatically_set_glyph_code: false
  enable_configs_updater: true
  error_item:
    material: PODZOL
    excludeFromInventory: false # set to true if you don't want to display it inside inventory
    injectID: false

CustomArmor:
  disable_leather_repair: true # Makes custom armor not repairable with leather, only with copies of said custom armor

Misc:
  # If this is set to true, Oraxen will reset recipes on reload. This might create conflicts with other plugins
  # but this makes the things easier if you want to try your oraxen recipes.
  reset_recipes: true
  
  # This will hide the red numbers on the side of scoreboards
  hide_scoreboard_numbers: false
  
  # Update the items in player inventory to the latest in config when player joins
  auto_update_items: false
  
  # All blocks with an inventory or any blocks that when right clicked shouldn't equip armor.
  armor_equip_event_bypass:
  - FURNACE
  - CHEST
  - TRAPPED_CHEST
  - BEACON
  - DISPENSER
  - DROPPER
  - HOPPER
  - WORKBENCH
  - ENCHANTMENT_TABLE
  - ENDER_CHEST
  - ANVIL
  - BED_BLOCK
  - FENCE_GATE
  - SPRUCE_FENCE_GATE
  - BIRCH_FENCE_GATE
  - ACACIA_FENCE_GATE
  - JUNGLE_FENCE_GATE
  - DARK_OAK_FENCE_GATE
  - IRON_DOOR_BLOCK
  - WOODEN_DOOR
  - SPRUCE_DOOR
  - BIRCH_DOOR
  - JUNGLE_DOOR
  - ACACIA_DOOR
  - DARK_OAK_DOOR
  - WOOD_BUTTON
  - STONE_BUTTON
  - TRAP_DOOR
  - IRON_TRAPDOOR
  - DIODE_BLOCK_OFF
  - DIODE_BLOCK_ON
  - REDSTONE_COMPARATOR_OFF
  - REDSTONE_COMPARATOR_ON
  - FENCE
  - SPRUCE_FENCE
  - BIRCH_FENCE
  - JUNGLE_FENCE
  - DARK_OAK_FENCE
  - ACACIA_FENCE
  - NETHER_FENCE
  - BREWING_STAND
  - CAULDRON
  - LEGACY_SIGN_POST
  - LEGACY_WALL_SIGN
  - LEGACY_SIGN
  - ACACIA_SIGN
  - ACACIA_WALL_SIGN
  - BIRCH_SIGN
  - BIRCH_WALL_SIGN
  - DARK_OAK_SIGN
  - DARK_OAK_WALL_SIGN
  - JUNGLE_SIGN
  - JUNGLE_WALL_SIGN
  - OAK_SIGN
  - OAK_WALL_SIGN
  - SPRUCE_SIGN
  - SPRUCE_WALL_SIGN
  - LEVER
  - BLACK_SHULKER_BOX
  - BLUE_SHULKER_BOX
  - BROWN_SHULKER_BOX
  - CYAN_SHULKER_BOX
  - GRAY_SHULKER_BOX
  - GREEN_SHULKER_BOX
  - LIGHT_BLUE_SHULKER_BOX
  - LIME_SHULKER_BOX
  - MAGENTA_SHULKER_BOX
  - ORANGE_SHULKER_BOX
  - PINK_SHULKER_BOX
  - PURPLE_SHULKER_BOX
  - RED_SHULKER_BOX
  - SILVER_SHULKER_BOX
  - WHITE_SHULKER_BOX
  - YELLOW_SHULKER_BOX
  - DAYLIGHT_DETECTOR_INVERTED
  - DAYLIGHT_DETECTOR
  - BARREL
  - BLAST_FURNACE
  - SMOKER
  - CARTOGRAPHY_TABLE
  - COMPOSTER
  - GRINDSTONE
  - LECTERN
  - LOOM
  - STONECUTTER
  - BELL
  
  # If you want to add shields, Oraxen needs to setup the display options of the default shield, here are the vanilla ones:
  shield_display: '{"thirdperson_righthand":{"rotation":[0,90,0],"translation":[10,6,-4],"scale":[1,1,1]},"thirdperson_lefthand":{"rotation":[0,90,0],"translation":[10,6,12],"scale":[1,1,1]},"firstperson_righthand":{"rotation":[0,180,5],"translation":[-10,2,-10],"scale":[1.25,1.25,1.25]},"firstperson_lefthand":{"rotation":[0,180,5],"translation":[10,0,-10],"scale":[1.25,1.25,1.25]},"gui":{"rotation":[15,-25,-5],"translation":[2,3,0],"scale":[0.65,0.65,0.65]},"fixed":{"rotation":[0,180,0],"translation":[-2,4,-5],"scale":[0.5,0.5,0.5]},"ground":{"rotation":[0,0,0],"translation":[4,4,2],"scale":[0.25,0.25,0.25]}}'
  
  # Same for bows:
  bow_display: '{"thirdperson_righthand":{"rotation":[-80,260,-40],"translation":[-1,-2,2.5],"scale":[0.9,0.9,0.9]},"thirdperson_lefthand":{"rotation":[-80,-280,40],"translation":[-1,-2,2.5],"scale":[0.9,0.9,0.9]},"firstperson_righthand":{"rotation":[0,-90,25],"translation":[1.13,3.2,1.13],"scale":[0.68,0.68,0.68]},"firstperson_lefthand":{"rotation":[0,90,-25],"translation":[1.13,3.2,1.13],"scale":[0.68,0.68,0.68]}}'
  
  # Same for crossbows:
  crossbow_display: '{"thirdperson_righthand":{"rotation":[-90,0,-60],"translation":[2,0.1,-3],"scale":[0.9,0.9,0.9]},"thirdperson_lefthand":{"rotation":[-90,0,30],"translation":[2,0.1,-3],"scale":[0.9,0.9,0.9]},"firstperson_righthand":{"rotation":[-90,0,-55],"translation":[1.13,3.2,1.13],"scale":[0.68,0.68,0.68]},"firstperson_lefthand":{"rotation":[-90,0,35],"translation":[1.13,3.2,1.13],"scale":[0.68,0.68,0.68]}}'

# Better customization for GUI oraxen inv. Oraxen Items Work. its gui_inventory.<name to file without extension yml>
gui_inventory:
  armors:
    icon: emerald_chestplate
    color: <#362753>
  blocks:
    icon: orax_ore
    color: <#EDCDEB>
  flowers:
    icon: dailily
    color: <#bf332c>
  hats:
    icon: crown
    color: <#81B125>
  items:
    icon: ruby
    color: <#DA2E45>
  mystical:
    icon: legendary_hammer
    color: <#9AB2E4>
  plants:
    icon: weed_leaf
    color: <#44C886>
  skins:
    icon: wood_sword
    color: <#C48E40>
  tools:
    icon: iron_serpe
    color: <#FFFFFF>
  weapons:
    icon: energy_crystal_sword
    color: <#2FB6FF>
```

Config containing single working glyph:
```
afktoken:
  texture: moul/icons/afktoken
  code: 5201
  ascent: 7
  height: 7
  chat:
    placeholders:
      - ":afktoken:"
    permission: "oraxen.emoji.afktoken"

auctionhouse:
  texture: moul/icons/auctionhouse
  code: 5202
  ascent: 7
  height: 7
  chat:
    placeholders:
      - ":auctionhouse:"
    permission: "oraxen.emoji.auctionhouse"

comingsoon:
  texture: moul/icons/comingsoon
  code: 5203
  ascent: 7
  height: 7
  chat:
    placeholders:
      - ":comingsoon:"
    permission: "oraxen.emoji.comingsoon"

cosmoshop:
  texture: moul/icons/cosmoshop
  code: 5204
  ascent: 7
  height: 7
  chat:
    placeholders:
      - ":cosmoshop:"
    permission: "oraxen.emoji.cosmoshop"

cosmotoken:
  texture: moul/icons/cosmotoken
  code: 5205
  ascent: 7
  height: 7
  chat:
    placeholders:
      - ":cosmotoken:"
    permission: "oraxen.emoji.cosmotoken"

discord:
  texture: moul/icons/discord
  code: 5206
  ascent: 7
  height: 7
  chat:
    placeholders:
      - ":discord:"
    permission: "oraxen.emoji.discord"

greenstore:
  texture: moul/icons/greenstore
  code: 5207
  ascent: 7
  height: 7
  chat:
    placeholders:
      - ":greenstore:"
    permission: "oraxen.emoji.greenstore"

latestdonator:
  texture: moul/icons/latestdonator
  code: 5208
  ascent: 7
  height: 7
  chat:
    placeholders:
      - ":latestdonator:"
    permission: "oraxen.emoji.latestdonator"

lifesteal:
  texture: moul/icons/lifesteal
  code: 5209
  ascent: 7
  height: 7
  chat:
    placeholders:
      - ":lifesteal:"
    permission: "oraxen.emoji.lifesteal"

menu:
  texture: moul/icons/menu
  code: 5210
  ascent: 7
  height: 7
  chat:
    placeholders:
      - ":menu:"
    permission: "oraxen.emoji.menu"

moul:
  texture: moul/icons/moul
  code: 5211
  ascent: 7
  height: 7
  chat:
    placeholders:
      - ":moul:"
    permission: "oraxen.emoji.moul"

pinkstore:
  texture: moul/icons/pinkstore
  code: 5212
  ascent: 7
  height: 7
  chat:
    placeholders:
      - ":pinkstore:"
    permission: "oraxen.emoji.pinkstore"

rtp:
  texture: moul/icons/rtp
  code: 5213
  ascent: 7
  height: 7
  chat:
    placeholders:
      - ":rtp:"
    permission: "oraxen.emoji.rtp"

tokenshop:
  texture: moul/icons/tokenshop
  code: 5214
  ascent: 7
  height: 7
  chat:
    placeholders:
      - ":tokenshop:"
    permission: "oraxen.emoji.tokenshop"

common:
  texture: moul/icons/common
  code: 5215
  ascent: 7
  height: 7
  chat:
    placeholders:
      - ":common:"
    permission: "oraxen.emoji.common"

uncommon:
  texture: moul/icons/uncommon
  code: 5216
  ascent: 7
  height: 7
  chat:
    placeholders:
      - ":uncommon:"
    permission: "oraxen.emoji.uncommon"

rare:
  texture: moul/icons/rare
  code: 5217
  ascent: 7
  height: 7
  chat:
    placeholders:
      - ":rare:"
    permission: "oraxen.emoji.rare"

legendary:
  texture: moul/icons/legendary
  code: 5218
  ascent: 7
  height: 7
  chat:
    placeholders:
      - ":legendary:"
    permission: "oraxen.emoji.legendary"

mythical:
  texture: moul/icons/mythical
  code: 5219
  ascent: 7
  height: 7
  chat:
    placeholders:
      - ":mythical:"
    permission: "oraxen.emoji.mythical"

```
Only working glyph was pinkstore
