### ISSUE TITLE
[BUG] ItemUpdater wipes itemmeta and in turn PDC

### ISSUE THREAD

**Issue by Taiyou06** [oraxen/oraxen#637]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Backpack mechanic works fine in the server but when the user logs out and logs in again trheir backpacks will be cleared.

### Steps to reproduce

1- make an item with backpack mechanic
2- throw some items in it
3- log out and log in
4- done

### Plugin Version

1.150.1

### ProtocolLib Version

5.0.0-SNAPSHOT-b608

### Server Software & Version

git-Purpur-1857 (MC: 1.19.2)

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable

**Comment by Boy0000** [comment]
@Taiyou06 entirely unable to reproduce this

```yml
backpack:
  displayname: "backpack"
  material: PAPER
  Mechanics:
    backpack:
      rows: 2
      title: "Test"
```

https://user-images.githubusercontent.com/62521371/212392522-3eec9d5f-e940-4821-b791-05a1073e42b2.mp4
