### ISSUE TITLE
[BUG] Metal sounds not working on Noteblock

### ISSUE THREAD

**Issue by botprzemek** [oraxen/oraxen#695]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

The bug occures when you try to use block_sounds and **block.metal.action*** on block mechanic **Noteblock.** I have tried using other types like **stone** or **glass** and they were working as they should. This is an **minor bug,** works without errors, Oraxen is just using the regular block.stone.action sounds.

_* action is block event like step or place_

### Steps to reproduce

```
custom_block:
  Mechanics:
    noteblock:
      block_sounds:
        break_sound: **block.metal.break**
        place_sound: **block.metal.place**
        hit_sound: **block.metal.hit**
        step_sound: **block.metal.step**
        fall_sound: **block.metal.fall**
```

### Plugin Version

**[00:35:44 INFO]:** Oraxen version **1.151.0**
**[00:35:44 INFO]:** Author: **Th0rgal**

### ProtocolLib Version

**[00:35:40 INFO]:** ProtocolLib version **5.0.0-SNAPSHOT-b612**
**[00:35:40 INFO]:** Provides read/write access to the Minecraft protocol.
**[00:35:40 INFO]:** Authors: **dmulloy2 and comphenix**

### Server Software & Version

**[00:35:33 INFO]:** Current: **git-Purpur-1632 (MC: 1.18.2)***
* You are running the latest version

_I don't really know if it's about the version of my server._

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects
