### ISSUE TITLE
[BUG] Custom namespace path for texture doesn't work for glyphs

### ISSUE THREAD

**Issue by GliczDev** [oraxen/oraxen#706]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Custom namespace path for texture doesn't work for glyphs
Example:
```yml
heart:
  texture: fazmc:chat/heart
  ascent: 8
  height: 8
  chat:
    placeholders:
      - "<3"
    permission: "oraxen.emoji.heart"
```

### Steps to reproduce

Create glyph like example above

### Plugin Version

1.151.0 (because of my PRs - custom build)

### ProtocolLib Version

5.0.0-SNAPSHOT-b612

### Server Software & Version

This server is running Paper version git-Paper-383 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: b082d89)

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects
