### ISSUE TITLE
[BUG] Minimal Type Speed Inconsistencies

### ISSUE THREAD

**Issue by cm4500** [oraxen/oraxen#728]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

When mining a custom block, there are inconsistencies with the "minimal_type" feature. 

I have made several different custom blocks using the included Oraxen blocks's format as the general template. In my case, these blocks are to be broken with pickaxes only. Different blocks have different minimal type such as wooden for basic stones, and iron for certain ores. What I have noticed is that the minimal type value and thus its gradual "better pickaxe, better mining speed" mechanic does not exactly work as intended. In my example, the pickaxes either have two speeds - slow or fast. There does not appear to be a gradual mechanic in place with gold mining faster than diamond generally, and so on and so forth. 

Listed below are all the results when the example block's minimal type value is set to each of the pickaxe types. Each type of pickaxe is then used on said block, with incorrect mining speeds but otherwise consistent results. Each includes the general mining speed expected by the block's hardness and whether or not the block drops. A reminder that there appear to only be two types of mining speeds, slow and fast. No gradually increasing speed based on the pickaxe's material. The slow speed also does not appear to consider the block's hardness, so setting it to 0 will still result in the same slow mining speed. 

WOODEN (every pickaxe will drop the block):
- Wooden - fast speed
- Stone - fast speed
- Iron - slow speed
- Gold - slow speed
- Diamond - slow speed
- Netherite - slow speed

STONE:
- Wooden - slow, does not drop
- Stone - fast, drops block
- Iron - fast, drops block
- Gold - slow, drops block
- Diamond - slow, drops block
- Netherite - slow, drops block

IRON:
- Wooden - slow, does not drop
- Stone - slow, does not drop
- Iron - fast, drops block
- Gold - fast, drops block
- Diamond - slow, drops block
- Netherite - slow, drops block

GOLDEN:
- Wooden - slow, does not drop
- Stone - slow, does not drop
- Iron - slow, does not drop
- Gold - fast, drops block
- Diamond - fast, drops block
- Netherite - slow, drops block

DIAMOND:
- Wooden - slow, does not drop
- Stone - slow, does not drop
- Iron - slow, does not drop
- Gold - fast, drops block
- Diamond - fast, drops block
- Netherite - slow, drops block

NETHERITE:
- Wooden - slow, does not drop
- Stone - slow, does not drop
- Iron - slow, does not drop
- Gold - slow, does not drop
- Diamond - slow, does not drop
- Netherite - fast, drops block

Based on the results, it appears that whatever the minimal type value is plus the immediate next tier material mines the block fast, with all other types mining slow. The dropping mechanic works perfectly. So it is only the mining speed part of the code that is somehow not working correctly. 

### Steps to reproduce

```yml
fuchsite:
  displayname: '<#FFFFFF>Fuchsite'
  material: PAPER
  Pack:
    generate_model: true
    parent_model: block/cube_all
    textures:
      - default/blocks/fuchsite
  Mechanics:
    noteblock:
      block_sounds:
        break_sound: block.stone.break
        place_sound: block.stone.place
      custom_variation: 27
      model: fuchsite
      hardness: 1.5
      drop:
        silktouch: false
        fortune: false
        minimal_type: WOODEN
        best_tools:
          - PICKAXE
        loots:
          - { oraxen_item: fuchsite, probability: 1.0 }`

This is the code for the block. All blocks in my server use this format as copied from the default oraxen blocks. Changing the minimal_type value should replicate the results. 

### Plugin Version

07.03 05:08:38 [Server] [INFO] oraxen version 1.152.3
07.03 05:08:38 [Server] [INFO] Authors: th0rgal and boy0000

### ProtocolLib Version

07.03 05:09:07 [Server] [INFO] ProtocolLib version 5.0.0-SNAPSHOT-b614
07.03 05:09:07 [Server] [INFO] Provides read/write access to the Minecraft protocol.
07.03 05:09:07 [Server] [INFO] Authors: dmulloy2 and comphenix

### Server Software & Version

07.03 05:09:21 [Server] [INFO] This server is running Paper version git-Paper-"cd215af" (MC: 1.19) (Implementing API version 1.19-R0.1-SNAPSHOT) (Git: cd215af)
07.03 05:09:21 [Server] [INFO] You are 475 version(s) behind
07.03 05:09:21 [Server] [INFO] Download the new version at: https://papermc.io/downloads

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects

**Comment by cm4500** [comment]
As of now, I have updated paper to the latest version. The same results exist.

**Comment by cm4500** [comment]
I have modified the block code to include a list of all pickaxe types. This fixes the pickaxe types not registering. But a consequence of this is that the hardness value and pickaxe mining speed do not correlate to their vanilla counterparts. 

Fuchsite is suppose to be another block just like diorite, andesite, etc. Those vanilla blocks have a hardness of 1.5. With fuchsite, I have to set the hardness to 6 to have the mining speed with a wooden pickaxe be about the same. And even then, the mining speed difference with an efficiency 5 netherite pickaxe between vanilla diorite and this custom fuchsite is very notable. 

```
fuchsite:
  displayname: '<#FFFFFF>Fuchsite'
  material: PAPER
  Pack:
    generate_model: true
    parent_model: block/cube_all
    textures:
      - default/blocks/fuchsite
  Mechanics:
    noteblock:
      block_sounds:
        break_sound: block.stone.break
        place_sound: block.stone.place
      custom_variation: 27
      model: fuchsite
      hardness: 6
      drop:
        minimal_type: 
          - WOODEN
          - STONE
          - IRON
          - GOLD
          - DIAMOND
          - NETHERITE
        best_tools:
          - PICKAXE
        loots:
          - { oraxen_item: fuchsite, probability: 1.0 }

```
