### ISSUE TITLE
[BUG] Issues with Oraxen Custom Crops

### ISSUE THREAD

**Issue by cm4500** [oraxen/oraxen#760]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

The custom crop mechanic built into Oraxen has a repeating issue where when crops grow into their next stage (such as seeds to stage0, stage1, stage2, etc), they often will revert back to their immediate previous stage more often than not (stage0 > stage1 > stage0). Eventually the crops do commit to the next stage without reverting back so eventually they ALL will get to the final stage and stay there, but there is no rhyme or reason why they sometimes revert back and sometimes do not. 

The crops, being furniture, are technically item frames. When switching between stages, the number of entities doubles to show the next stage before slowly removing the duplicates. So if there are 1 crop planted, the moment it grows into the stage stage, the entity count will go from 1 to 2. Then when it reverts back to the previous stage, the entity count goes back to 1. Sometimes the entity count simply goes up from 1 to 2 to 3, though I cannot find a correlation as to why this happens. Upon breaking the crop when there are duplicate stages still present, you can get loot for every single one of these, making you get way more loot than you should. 

If this duplication glitch gets bad enough, it will create so many entities that it will crash the server. The most recent attempt of testing 5 crops led to massive lag over the course of 10 or so minutes. With /kill @e[type=item_frame,distance=16], the console showed I killed 76516 entities. This renders custom crops with Oraxen as a game-breaking bug, but since I cannot duplicate this glitch on command, I list this as a Non-breaking bug. 

I assume the duplication is how the crops technically "grow" from stage to stage - where one entity is stage0 and the next one is stage1. And it is _suppose_ to clear the previous stage thus making the crop "grow". But it seems that it often clears the wrong one, which is why crops appear to revert back into previous stages. 

### Steps to reproduce

Here are the crop files I have in question. Using this should replicate the glitch. This has been tested with all other plugins disabled and the results were the same. Note that the delay value has been set to 100 for the sake of testing. Higher values yield the same results.

```yml
grape_seeds:
  displayname: "<#FFFFFF>Grape Seeds"
  material: PAPER
  Mechanics:
    furniture:
      limited_placing:
        roof: false
        floor: true
        wall: false
        type: ALLOW
        block_types:
          - FARMLAND
      item: grape_stage0
      barrier: false
      farmblock_required: false
      evolution:
        delay: 100
        probability: 1.0
        light_boost: false
        next_stage: grape_stage0
      drop:
        minimal_type: WOODEN
        loots:
          - { oraxen_item: grape_seeds, probability: 1.00 }
  Pack:
    generate_model: true
    parent_model: "item/generated"
    custom_variation: 800
    textures:
      - default/grapes/grape_seeds

grape_stage0:
  material: PAPER
  excludeFromInventory: true
  Mechanics:
    furniture:
      limited_placing:
        roof: false
        floor: true
        wall: false
        type: ALLOW
        block_types:
          - FARMLAND
      barrier: false
      farmblock_required: false
      evolution:
        delay: 100
        probability: 1.0
        light_boost: false
        next_stage: grape_stage1
      drop:
        silktouch: false
        minimal_type: WOODEN
        loots:
          - { oraxen_item: grape_seeds, max_amount: 1, probability: 1.00 }
  Pack:
    generate_model: false
    custom_variation: 801
    model: default/crops/grapes/grapes_stage0

grape_stage1:
  material: PAPER
  excludeFromInventory: true
  Mechanics:
    furniture:
      limited_placing:
        roof: false
        floor: true
        wall: false
        type: ALLOW
        block_types:
          - FARMLAND
      barrier: false
      farmblock_required: false
      evolution:
        delay: 10000
        probability: 1.0
        light_boost: false
        next_stage: grape_stage2
      drop:
        silktouch: false
        minimal_type: WOODEN
        loots:
          - { oraxen_item: grape_seeds, max_amount: 1, probability: 1.00 }
  Pack:
    generate_model: false
    custom_variation: 802
    model: default/crops/grapes/grapes_stage1

grape_stage2:
  material: PAPER
  excludeFromInventory: true
  Mechanics:
    furniture:
      limited_placing:
        roof: false
        floor: true
        wall: false
        type: ALLOW
        block_types:
          - FARMLAND
      barrier: false
      farmblock_required: false
      evolution:
        delay: 100
        probability: 1.0
        light_boost: false
        next_stage: grape_stage3
      drop:
        silktouch: false
        minimal_type: WOODEN
        loots:
          - { oraxen_item: grape_seeds, max_amount: 1, probability: 1.00 } 
  Pack:
    generate_model: false
    custom_variation: 803
    model: default/crops/grapes/grapes_stage2

grape_stage3:
  material: PAPER
  excludeFromInventory: true
  Mechanics:
    furniture:
      limited_placing:
        roof: false
        floor: true
        wall: false
        type: ALLOW
        block_types:
          - FARMLAND
      barrier: false
      farmblock_required: false
      evolution:
        delay: 100
        probability: 1.0
        light_boost: false
        next_stage: grape_stage4
      drop:
        silktouch: false
        minimal_type: WOODEN
        loots:
          - { oraxen_item: grape_seeds, max_amount: 1, probability: 1.00 }
  Pack:
    generate_model: false
    custom_variation: 804
    model: default/crops/grapes/grapes_stage3

grape_stage4:
  material: PAPER
  excludeFromInventory: true
  Mechanics:
    furniture:
      limited_placing:
        roof: false
        floor: true
        wall: false
        type: ALLOW
        block_types:
          - FARMLAND
      barrier: false
      farmblock_required: false
      drop:
        silktouch: false
        minimal_type: WOODEN
        loots:
          - { oraxen_item: grape_seeds, probability: 1.00 }
          - { oraxen_item: grape_seeds, probability: 0.67 }
          - { oraxen_item: grape_seeds, probability: 0.50 }
          - { oraxen_item: grape_seeds, probability: 0.25 }
          - { oraxen_item: grapes, probability: 1.00 }
          - { oraxen_item: grapes, probability: 0.5 }
          - { oraxen_item: grapes, probability: 0.25 }
  Pack:
    generate_model: false
    custom_variation: 805
    model: default/crops/grapes/grapes_stage4
```

### Plugin Version

21.03 06:20:01 [Server] [INFO] oraxen version 1.152.3
21.03 06:20:01 [Server] [INFO] Authors: th0rgal and boy0000

### ProtocolLib Version

21.03 06:19:46 [Server] [INFO] ProtocolLib version 5.0.0-SNAPSHOT-b614
21.03 06:19:46 [Server] [INFO] Provides read/write access to the Minecraft protocol.
21.03 06:19:46 [Server] [INFO] Authors: dmulloy2 and comphenix

### Server Software & Version

21.03 06:19:17 [Server] [INFO] This server is running Paper version git-Paper-"155aa36" (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 155aa36)

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable
