### ISSUE TITLE
[BUG] Furniture drops phasing through roof when placed right beneath it

### ISSUE THREAD

**Issue by TheLaoming** [oraxen/oraxen#761]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Hey, 

With latest Oraxen i'm facing few bugs with furnitures. Mostly when you put the furniture upwards and destroy it, it's buggy and it's stuck here. Probably only item frame, but you can't hit it sometimes and that's really annoying. Similar problem i've found with non barrier furnitures. The real problem is, that a lot of players lost their furnitures somehow when they have decided to destroy it.

### Steps to reproduce

Put this furniture upwards on a block:
```
TEST_furniture_1:
  displayname: " <#43a5e0>Test"
  lore:
  - <gray>Decoration
  material: LEATHER_HORSE_ARMOR
  color: 255, 255, 255
  ItemFlags:
    - HIDE_DYE
    - HIDE_ENCHANTS
  Mechanics:
    hardness: 1
    furniture:
      block_sounds:
        place_sound: minecraft:block.stone.place
        break_sound: minecraft:block.stone.break
        volume: 0.8
        pitch: 0.8
      facing: UP
      barriers:
        - { x: 0, y: 0, z: 0 }
      drop:
        silktouch: false
        loots:
          - { oraxen_item: TEST_furniture_1, probability: 1.0 }
  Pack:
    generate_model: false
    model: item/gamerealms/test/test_1
    custom_model_data: 41
```

or this:

```
TEST_furniture_2:
  displayname: "<#43a5e0>Test 2"
  lore:
  - <gray>Decoration
  material: LEATHER_HORSE_ARMOR
  ItemFlags:
    - HIDE_DYE
    - HIDE_ENCHANTS
  Mechanics:
    hardness: 1
    furniture:
      block_sounds:
        place_sound: minecraft:block.stone.place
        break_sound: minecraft:block.stone.break
        volume: 0.8
        pitch: 0.8
      rotation: NONE
      drop:
        silktouch: false
        loots:
          - { oraxen_item: TEST_furniture_2, probability: 1.0 }
  Pack:
    generate_model: false
    model: item/gamerealms/test/test_2
    custom_model_data: 40
```

And destroy it. Don't know if it's my configuration, but it's buggy.
Same problem are furnitures placed while facing north/east, they will break like this. Sometimes they don't even fall out or you can see the model of the furniture, but you can harldy destroy it. It often happens that decorations get stuck in the wall (that's happen for all of the furnitures, especially if there is a block above them). Almost every day someone say that their furniture will disappear after break.

And this is, very often. Someone destroy their furniture and it's moved to the highest block above the destroyed decoration (if there's any block above furniture's current location). So for example if you destroy a custom chest, placed on ceiling, and you're 50 blocks underground, good luck. Because that furniture wil be moved all the way to the top and then probably after some time despawn. I have seen this with vanilla item frames few mc versions before. Don't know it it's still an issue.

**Solution:** Furnitures could be moved right to the player or into their inventory better.

I'm able to send some videos, but only on discord, there's 10MB size limit.

### Plugin Version

1.153.1

### ProtocolLib Version

ProtocolLib version 5.0.0-SNAPSHOT-b615

### Server Software & Version

This server is running Paper version git-Paper-307 (MC: 1.19.2)

### How breaking is the bug?

Breaking Bug - Plugin unusable
