### ISSUE TITLE
[BUG] Custom items with barrier material does not work

### ISSUE THREAD

**Issue by L1ghtDream** [oraxen/oraxen#782]
### I have checked...

- [x] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Barrier items does not change its texture.

### Steps to reproduce

Add 2 items
```yml
transparent1:
  displayname: "[ADMIN_ONLY]"
  material: BARRIER
  Pack:
    generate_model: true
    parent_model: "item/handheld"
    textures:
      - transparent.png
transparent2:
  displayname: "[ADMIN_ONLY]"
  material: DIAMOND_AXE
  Pack:
    generate_model: true
    parent_model: "item/handheld"
    textures:
      - transparent.png
```

Give yourself both items

### Plugin Version

1.153.0

### ProtocolLib Version

5.0.0-SNAPSHOT-b612

### Server Software & Version

arclight-1.19.2-1.0.1-0550c6cd

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects
