### ISSUE TITLE
[BUG] Turtle eggs with custom texture not working

### ISSUE THREAD

**Issue by hugohuetzel** [oraxen/oraxen#866]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Creating turtle eggs with a custom texture does not work.

Example config:
```
easter_egg_red:
  displayname: <white>Red Easter Egg
  material: TURTLE_EGG
  Pack:
    generate_model: true
    parent_model: item/generated
    textures:
    - item/disaster/easter_egg_red
    custom_model_data: 100025
```
It doesn't work because the turtle_egg.json file is missing in the generated pack.zip.

### Steps to reproduce

Try with example config

### Plugin Version

Oraxen version 1.156.4

### ProtocolLib Version

ProtocolLib version 5.1.0-SNAPSHOT-645

### Server Software & Version

This server is running Paper version git-Paper-545 (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: bacbf86)

### How breaking is the bug?

Non-breaking Bug - Plugin still usable, but certain features unavailable
