### ISSUE TITLE
[SUGGESTION] clickactions SOUND!

### ISSUE THREAD

**Issue by itsMarkiS** [oraxen/oraxen#880]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

basically, add a clickaction that plays a sound when you rightclick the block
at the moment i have to use this

![image](https://github.com/oraxen/oraxen/assets/47507632/f0af3890-3c37-494c-9f95-a7c2512396a3)

following the example, it could be like this

```
      clickActions:
      - conditions: []
        actions:
        - '[sound] entity_slime_squish  -v:0.25 -p:0.8'
        - '[sound] item_dye_use, volume:1.2, pitch:0.8'
```
or
```
      clickActions:
      - conditions: []
        sounds:
        -  item_dye_use, volume:1.2, pitch:0.8'
        -  entity_slime_squish  v:0.25 p:0.8'
```

### Reason

have to use console commands to produce sounds to the player is kinda  bad imo
