### ISSUE TITLE
[SUGGESTION] Recipe : add an amount to the result itemstack

### ISSUE THREAD

**Issue by ComminQ** [oraxen/oraxen#882]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

For example, we say that we have two customs items, a ruby and a ruby blocks, and we want to add a conversion from one to another and vice-versa. We need to code the following thing:

```yaml
ruby_block:
  shape:
    - AAA
    - AAA
    - AAA
  result:
    oraxen_item: ruby_block
  ingredients:
    A:
      oraxen_item: ruby
ruby_block_back:
  shape:
    - A
  result:
    oraxen_item: ruby
  ingredients:
    A:
      oraxen_item: ruby_block
```

We can't set the amount of the resulting item in the recipe.

We could have a amount parameter at the result section like the following :

```yaml
ruby_block_back:
  shape:
    - A
  result:
    oraxen_item: ruby
    amount: 9
  ingredients:
    A:
      oraxen_item: ruby_block
```

It should be relatively easy to implement in the "io.th0rgal.oraxen.recipes.loaders.RecipeLoader" class.

### Reason

I think the example above is a pretty good reason.
Adding custom ores is something that a lot of servers does.
It would be cool to add such feature.
