### ISSUE TITLE
[SUGGESTION] Extra model for JukeboxMechanic

### ISSUE THREAD

**Issue by itsMarkiS** [oraxen/oraxen#888]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

Add an option to have an extra model/item
When the custom jukebox item is playing, it would swap its own model

Example 1:
```
radio:
  Mechanics:
      jukebox:
        volume: 1.0
        pitch: 1.0
        playing-model: custom/radio_play
        playing-model-data: 2
      drop:
        loots:
        - oraxen_item: radio
          probability: 1.0
  Pack:
    generate_model: false
    model: custom/radio
    custom_model_data: 1
```

Example 2:
In this other example, it is based in other item, in this example: "radio" is the main item, and when it starts playing, the model will change to the "radio_play" item 

```
radio:
  Mechanics:
      jukebox:
        volume: 1.0
        pitch: 1.0
        playing-model: radio_play
      drop:
        loots:
        - oraxen_item: radio
          probability: 1.0
  Pack:
    generate_model: false
    model: custom/radio

radio_play:
  Mechanics:
      jukebox:
        volume: 1.0
        pitch: 1.0
      drop:
        loots:
        - oraxen_item: radio
          probability: 1.0
  Pack:
    generate_model: false
    model: custom/radio_play
```

### Reason

it would be better to visualize whenever the custom jukebox is playing
and also its a cool small aesthetic detail

https://github.com/oraxen/oraxen/assets/47507632/71c2470c-6c8d-4599-aa26-09dd38ea5fd9
