### ISSUE TITLE
[SUGGESTION] Choose characters for glyphs

### ISSUE THREAD

**Issue by MarkinhosMLP** [oraxen/oraxen#913]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

Choose which characters would be applied to which image/emoji/glyph in general
here ill be showing some examples, using the default config/default examples in docs

```
heart:
  texture: default/chat/heart
  is_emoji: true
  chars:
  - '❤'
```
if you leave it empty, like this
```
heart:
  texture: default/chat/heart
  is_emoji: true
```
then oraxen will define it automatically
for multi glyphs we will be doing something a little bit different, based in the docs
![image](https://github.com/oraxen/oraxen/assets/47507632/5c4a20eb-469e-4a61-88b2-5a326337650d)

```
bitmaps:
  example_bitmap:
      texture: example/example_bitmap
      rows: 4
      columns: 9
      ascent: 8
      height: 8
      chars: 
      - '😀,😃,😄,😁,😆,😅,🤣,😂,🙂'
      - auto
      - auto
      - auto
```
since these have 4 rows, and 9 columns, each line will be a row, but what if you want to define one only and the rest to be automatically defined?
then it could be like
```
bitmaps:
  example_bitmap:
      texture: example/example_bitmap
      rows: 4
      columns: 9
      ascent: 8
      height: 8
      chars: 
      - '😀,<auto>,<auto>,<auto>,<auto>,<auto>,<auto>,<auto>,<auto>'
      - '<auto>'
      - '<auto>'
      - '<auto>'
```
or even
```
bitmaps:
  example_bitmap:
      texture: example/example_bitmap
      rows: 4
      columns: 9
      ascent: 8
      height: 8
      chars: 
      - '😀'
      - ''
      - ''
      - ''
```

or make it obligatory to fully select which character will be applied to each glyph in at least one row 

### Reason

Avoid conflicts, better management of glyphs for plugins which oraxen glyphs doesnt works
more liberty to customization
