### ISSUE TITLE
[SUGGESTION] Oraxen could change vanilla features

### ISSUE THREAD

**Issue by MarkinhosMLP** [oraxen/oraxen#922]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

THIS IS SOMETHING THAT I THINK WILL BE REALLY USEFUL, BUT REALLY COMPLICATED, so if possible, and if this suggestion gets accepted, maybe keep it like something for a future big update 

maybe we could use some different things, like using oraxen mechanics in vanilla items
for example, make fletching table open a container, using clickactions in a lit soul campfire execute a command, or make so every normal iron sword could use a energyblast effect for example

with that, you would need to ad something in the settings like "change-vanilla-features: true"
and a new yml for the vanilla features

in this one, you would have to specify the block and blockstate

one example i made

"Vanilla.yml"
```
healing_campfire:
      type: BLOCK ##or item
      block: CAMPFIRE ##item: if it is an item, of course
      blockstates: ##if it is an item, you can define some types of nbt like - mynbt: true - susnbt: 2
        - lit: true ##for blocks with different blockstates like lanterns, which have "hanging" and normal model, you wouldnt be able to use "true", you would have to specify
        - signal_campfire: true 
      limited_placing: ##you would also be able to limit vanilla blocks to be placed over others or in the floor/roof/wall
        roof: false
        floor: true
        wall: false
      storage:   ## you would be able to create storages mechanics with it
        type: STORAGE
        rows: 1
        title: Something 
        open_sound: block.chest.open
        close_sound: block.barrel.close
      drop:
        loots:
        - oraxen_item: custom_arrow ##you would be able to change the drop of a vanilla block or item
       clickActions: ##just as normal click actions works
      - conditions: []
        actions:
        - '[console] heal <player>'
## in this example pack option wouldnt do nothing, but maybe could change the vanilla model as well
```

### Reason

even more customization for oraxen, yay
(also, i wouldnt have to install like 5 plugins for one single feature, oraxen is da best)
