### ISSUE TITLE
[SUGGESTION] STRIP-Tool Option

### ISSUE THREAD

**Issue by MarkinhosMLP** [oraxen/oraxen#959]
### I have checked that...

- [X] ...such a feature does not exist already
- [X] ...such a feature request has not been submitted already

### Description

option to choose which tool type can "strip" the block

```
my_block:
  Mechanics:
    noteblock:
      logStrip:
        stripped_log: my_new_block
        strip_tools:
        - AXE
        - SHOVEL
        - HOE
        - PICKAXE
        - SWORD
```

### Reason

for example, if i dont want to make a custom wood, but a custom dirt block
i can select the tool to be a shovel or a hoe
