### ISSUE TITLE
[BUG] Seats do not apply&change when using /oraxen reload all&items

### ISSUE THREAD

**Issue by Unknow-Player-1** [oraxen/oraxen#975]
### I have checked...

- [X] I am using the latest version of Oraxen
- [X] I am using the latest version of any dependencies
- [X] I am using ProtocolLib 5.0
- [X] I have checked if any similar bug reports exist

### Description

Seats do not apply&change when using /oraxen reload all&items

### Steps to reproduce

place the seats to a furniture already existing or to be created, or you can also try changing the height value of the seats and finally run the /oraxen reload all command.

```yml
table:
  displayname: <gray>Table
  material: PAPER
  Mechanics:
    furniture:
      type: ITEM_FRAME # Valid types are ITEM_FRAME, GLOW_ITEM_FRAME & DISPLAY_ENTITY if server is 1.19.4>
      limited_placing:
        roof: false
        floor: true
        wall: false
      barrier: true
      seat:
        height: 0
```

### Plugin Version

oraxen-1.158.2

### ProtocolLib Version

5.1.0-SNAPSHOT-661

### Server Software & Version

1.20.1 paper build-84

### How breaking is the bug?

Minor Bug - Plugin completely functional, but features have non-working aspects
